/**
 * Korean martial arts techniques for each trigram stance
 */

import { KoreanTechnique } from "@/systems/vitalpoint";
import {
  CombatAttackType,
  DamageType,
  PlayerArchetype,
  TrigramStance,
} from "../../types/common";

// Base techniques for each trigram stance
export const TRIGRAM_TECHNIQUES: Record<
  TrigramStance,
  readonly KoreanTechnique[]
> = {
  // ============= ☰ 건 (GEON) - HEAVEN: Direct Force Techniques (Taekwondo Power Strikes) =============
  [TrigramStance.GEON]: [
    {
      id: "geon_heaven_strike",
      // Note: Both 'name' object and separate fields maintained for backward compatibility
      // Tests and existing code may reference either format
      name: {
        korean: "천둥벽력",
        english: "Thunder Strike",
        romanized: "cheondung_byeokryeok",
      },
      koreanName: "천둥벽력",
      englishName: "Thunder Strike",
      romanized: "cheondung_byeokryeok",
      description: {
        korean: "하늘의 힘을 담은 직접적인 타격",
        english: "Direct strike imbued with heavenly power",
      },
      stance: TrigramStance.GEON,
      type: CombatAttackType.STRIKE,
      damageType: DamageType.BLUNT,
      damage: 30,
      kiCost: 15,
      staminaCost: 20,
      accuracy: 0.8,
      range: 1.2,
      executionTime: 800,
      recoveryTime: 1200,
      critChance: 0.1,
      critMultiplier: 1.5,
      effects: [],
    },
    {
      id: "geon_heavenly_fist",
      name: {
        korean: "천권",
        english: "Heavenly Fist",
        romanized: "cheon-gwon",
      },
      koreanName: "천권",
      englishName: "Heavenly Fist",
      romanized: "cheon-gwon",
      description: {
        korean: "태권도 정권지르기로 머리를 노리는 강력한 주먹 공격",
        english: "Powerful Taekwondo straight punch targeting the head",
      },
      stance: TrigramStance.GEON,
      type: CombatAttackType.PUNCH,
      damageType: DamageType.BLUNT,
      damage: 28,
      kiCost: 12,
      staminaCost: 15,
      accuracy: 0.85,
      range: 1.0,
      executionTime: 600,
      recoveryTime: 900,
      critChance: 0.12,
      critMultiplier: 1.6,
      effects: [],
    },
    {
      id: "geon_frontal_kick",
      name: {
        korean: "앞차기",
        english: "Front Kick",
        romanized: "ap-chagi",
      },
      koreanName: "앞차기",
      englishName: "Front Kick",
      romanized: "ap-chagi",
      description: {
        korean: "태권도 기본 앞차기로 명치를 타격",
        english: "Taekwondo basic front kick targeting solar plexus",
      },
      stance: TrigramStance.GEON,
      type: CombatAttackType.KICK,
      damageType: DamageType.BLUNT,
      damage: 32,
      kiCost: 18,
      staminaCost: 22,
      accuracy: 0.82,
      range: 1.5,
      executionTime: 700,
      recoveryTime: 1000,
      critChance: 0.15,
      critMultiplier: 1.7,
      effects: [],
    },
    {
      id: "geon_roundhouse_kick",
      name: {
        korean: "돌려차기",
        english: "Roundhouse Kick",
        romanized: "dolryeo-chagi",
      },
      koreanName: "돌려차기",
      englishName: "Roundhouse Kick",
      romanized: "dolryeo-chagi",
      description: {
        korean: "태권도 대표 기술로 관자놀이나 늑골을 타격하는 회전 발차기",
        english: "Signature Taekwondo spinning kick targeting temple or ribs",
      },
      stance: TrigramStance.GEON,
      type: CombatAttackType.KICK,
      damageType: DamageType.BLUNT,
      damage: 35,
      kiCost: 20,
      staminaCost: 25,
      accuracy: 0.78,
      range: 1.8,
      executionTime: 800,
      recoveryTime: 1100,
      critChance: 0.18,
      critMultiplier: 1.8,
      effects: [],
    },
    {
      id: "geon_axe_kick",
      name: {
        korean: "내려차기",
        english: "Axe Kick",
        romanized: "naeryeo-chagi",
      },
      koreanName: "내려차기",
      englishName: "Axe Kick",
      romanized: "naeryeo-chagi",
      description: {
        korean: "위에서 아래로 내리찍는 도끼차기로 정수리나 어깨를 타격",
        english: "Downward axe kick striking crown or shoulder from above",
      },
      stance: TrigramStance.GEON,
      type: CombatAttackType.KICK,
      damageType: DamageType.CRUSHING,
      damage: 38,
      kiCost: 22,
      staminaCost: 28,
      accuracy: 0.75,
      range: 1.6,
      executionTime: 900,
      recoveryTime: 1200,
      critChance: 0.20,
      critMultiplier: 2.0,
      effects: [],
    },
    {
      id: "geon_palm_strike",
      name: {
        korean: "장권",
        english: "Palm Strike",
        romanized: "jang-gwon",
      },
      koreanName: "장권",
      englishName: "Palm Strike",
      romanized: "jang-gwon",
      description: {
        korean: "태권도 장권으로 턱이나 명치를 타격하는 손바닥 공격",
        english: "Taekwondo palm heel strike targeting jaw or solar plexus",
      },
      stance: TrigramStance.GEON,
      type: CombatAttackType.STRIKE,
      damageType: DamageType.BLUNT,
      damage: 30,
      kiCost: 14,
      staminaCost: 18,
      accuracy: 0.88,
      range: 1.1,
      executionTime: 650,
      recoveryTime: 950,
      critChance: 0.14,
      critMultiplier: 1.6,
      effects: [],
    },
    {
      id: "geon_elbow_smash",
      name: {
        korean: "팔꿈치치기",
        english: "Elbow Smash",
        romanized: "palkkumchi-chigi",
      },
      koreanName: "팔꿈치치기",
      englishName: "Elbow Smash",
      romanized: "palkkumchi-chigi",
      description: {
        korean: "근거리에서 팔꿈치로 관자놀이나 턱을 강타",
        english: "Close-range elbow strike to temple or jaw",
      },
      stance: TrigramStance.GEON,
      type: CombatAttackType.ELBOW,
      damageType: DamageType.BLUNT,
      damage: 33,
      kiCost: 16,
      staminaCost: 20,
      accuracy: 0.86,
      range: 0.8,
      executionTime: 550,
      recoveryTime: 850,
      critChance: 0.16,
      critMultiplier: 1.8,
      effects: [],
    },
  ],
  // ============= ☱ 태 (TAE) - LAKE: Fluid Joint Manipulation (Hapkido Techniques) =============
  [TrigramStance.TAE]: [
    {
      id: "tae_flowing_strikes",
      name: {
        korean: "유수연타",
        english: "Flowing Strikes",
        romanized: "yusu_yeonta",
      },
      koreanName: "유수연타",
      englishName: "Flowing Strikes",
      romanized: "yusu_yeonta",
      description: {
        korean: "물의 흐름처럼 연속적인 타격",
        english: "Continuous strikes like flowing water",
      },
      stance: TrigramStance.TAE,
      type: CombatAttackType.STRIKE,
      damageType: DamageType.BLUNT,
      damage: 25,
      kiCost: 12,
      staminaCost: 18,
      accuracy: 0.85,
      range: 1.0,
      executionTime: 600,
      recoveryTime: 1000,
      critChance: 0.08,
      critMultiplier: 1.3,
      effects: [],
    },
    {
      id: "tae_wrist_lock",
      name: {
        korean: "손목꺾기",
        english: "Wrist Lock",
        romanized: "sonmok-kkeokgi",
      },
      koreanName: "손목꺾기",
      englishName: "Wrist Lock",
      romanized: "sonmok-kkeokgi",
      description: {
        korean: "합기도 손목 관절기로 상대를 제압",
        english: "Hapkido wrist joint lock for control",
      },
      stance: TrigramStance.TAE,
      type: CombatAttackType.GRAPPLE,
      damageType: DamageType.JOINT,
      damage: 22,
      kiCost: 10,
      staminaCost: 15,
      accuracy: 0.88,
      range: 0.7,
      executionTime: 700,
      recoveryTime: 1000,
      critChance: 0.12,
      critMultiplier: 1.5,
      effects: [],
    },
    {
      id: "tae_small_circle",
      name: {
        korean: "소원법",
        english: "Small Circle Technique",
        romanized: "sowon-beop",
      },
      koreanName: "소원법",
      englishName: "Small Circle Technique",
      romanized: "sowon-beop",
      description: {
        korean: "합기도 소원 기법으로 손목과 팔꿈치를 동시에 제압",
        english: "Hapkido small circle method controlling wrist and elbow",
      },
      stance: TrigramStance.TAE,
      type: CombatAttackType.GRAPPLE,
      damageType: DamageType.JOINT,
      damage: 24,
      kiCost: 14,
      staminaCost: 18,
      accuracy: 0.86,
      range: 0.8,
      executionTime: 750,
      recoveryTime: 1100,
      critChance: 0.14,
      critMultiplier: 1.6,
      effects: [],
    },
    {
      id: "tae_finger_lock",
      name: {
        korean: "손가락꺾기",
        english: "Finger Lock",
        romanized: "songarak-kkeokgi",
      },
      koreanName: "손가락꺾기",
      englishName: "Finger Lock",
      romanized: "songarak-kkeokgi",
      description: {
        korean: "합기도 소관절기로 손가락을 제압하여 무장 해제",
        english: "Hapkido small joint manipulation for disarming",
      },
      stance: TrigramStance.TAE,
      type: CombatAttackType.GRAPPLE,
      damageType: DamageType.JOINT,
      damage: 18,
      kiCost: 8,
      staminaCost: 12,
      accuracy: 0.90,
      range: 0.6,
      executionTime: 650,
      recoveryTime: 900,
      critChance: 0.10,
      critMultiplier: 1.4,
      effects: [],
    },
    {
      id: "tae_elbow_lock",
      name: {
        korean: "팔꿈치꺾기",
        english: "Elbow Lock",
        romanized: "palkkumchi-kkeokgi",
      },
      koreanName: "팔꿈치꺾기",
      englishName: "Elbow Lock",
      romanized: "palkkumchi-kkeokgi",
      description: {
        korean: "합기도 팔꿈치 관절기로 팔을 과신전시켜 제압",
        english: "Hapkido elbow hyperextension for submission",
      },
      stance: TrigramStance.TAE,
      type: CombatAttackType.GRAPPLE,
      damageType: DamageType.JOINT,
      damage: 26,
      kiCost: 16,
      staminaCost: 20,
      accuracy: 0.84,
      range: 0.9,
      executionTime: 800,
      recoveryTime: 1150,
      critChance: 0.16,
      critMultiplier: 1.7,
      effects: [],
    },
    {
      id: "tae_shoulder_lock",
      name: {
        korean: "어깨꺾기",
        english: "Shoulder Lock",
        romanized: "eokkae-kkeokgi",
      },
      koreanName: "어깨꺾기",
      englishName: "Shoulder Lock",
      romanized: "eokkae-kkeokgi",
      description: {
        korean: "합기도 어깨 관절기로 팔을 뒤로 비틀어 제압",
        english: "Hapkido shoulder manipulation twisting arm behind",
      },
      stance: TrigramStance.TAE,
      type: CombatAttackType.GRAPPLE,
      damageType: DamageType.JOINT,
      damage: 28,
      kiCost: 18,
      staminaCost: 22,
      accuracy: 0.82,
      range: 1.0,
      executionTime: 850,
      recoveryTime: 1200,
      critChance: 0.18,
      critMultiplier: 1.8,
      effects: [],
    },
    {
      id: "tae_arm_bar",
      name: {
        korean: "팔꺾기",
        english: "Arm Bar",
        romanized: "pal-kkeokgi",
      },
      koreanName: "팔꺾기",
      englishName: "Arm Bar",
      romanized: "pal-kkeokgi",
      description: {
        korean: "합기도 팔꺾기로 팔꿈치를 고정하여 항복을 유도",
        english: "Hapkido arm bar immobilizing elbow for submission",
      },
      stance: TrigramStance.TAE,
      type: CombatAttackType.GRAPPLE,
      damageType: DamageType.JOINT,
      damage: 30,
      kiCost: 20,
      staminaCost: 25,
      accuracy: 0.80,
      range: 1.1,
      executionTime: 900,
      recoveryTime: 1300,
      critChance: 0.20,
      critMultiplier: 1.9,
      effects: [],
    },
  ],
  // ============= ☲ 리 (LI) - FIRE: Precision Nerve Strikes (Taekwondo Accuracy) =============
  [TrigramStance.LI]: [
    {
      id: "li_flame_spear",
      name: {
        korean: "화염지창",
        english: "Flame Spear",
        romanized: "hwayeom_jichang",
      },
      koreanName: "화염지창",
      englishName: "Flame Spear",
      romanized: "hwayeom_jichang",
      description: {
        korean: "불꽃처럼 정확하고 날카로운 공격",
        english: "Precise and sharp attack like flame",
      },
      stance: TrigramStance.LI,
      type: CombatAttackType.THRUST,
      damageType: DamageType.PIERCING,
      damage: 35,
      kiCost: 18,
      staminaCost: 15,
      accuracy: 0.9,
      range: 1.5,
      executionTime: 700,
      recoveryTime: 1100,
      critChance: 0.15,
      critMultiplier: 1.8,
      effects: [],
    },
    {
      id: "li_temple_strike",
      name: {
        korean: "관자놀이타격",
        english: "Temple Strike",
        romanized: "gwanja-nori-tagyeok",
      },
      koreanName: "관자놀이타격",
      englishName: "Temple Strike",
      romanized: "gwanja-nori-tagyeok",
      description: {
        korean: "태권도 역권으로 관자놀이를 정확히 타격",
        english: "Taekwondo back fist precisely targeting temple",
      },
      stance: TrigramStance.LI,
      type: CombatAttackType.STRIKE,
      damageType: DamageType.NERVE,
      damage: 32,
      kiCost: 16,
      staminaCost: 18,
      accuracy: 0.92,
      range: 1.2,
      executionTime: 650,
      recoveryTime: 950,
      critChance: 0.22,
      critMultiplier: 2.0,
      effects: [],
    },
    {
      id: "li_nerve_strike",
      name: {
        korean: "신경타격",
        english: "Nerve Strike",
        romanized: "singyeong-tagyeok",
      },
      koreanName: "신경타격",
      englishName: "Nerve Strike",
      romanized: "singyeong-tagyeok",
      description: {
        korean: "정확한 손가락 타격으로 신경을 마비시킴",
        english: "Precise finger strike paralyzing nerves",
      },
      stance: TrigramStance.LI,
      type: CombatAttackType.NERVE_STRIKE,
      damageType: DamageType.NERVE,
      damage: 28,
      kiCost: 22,
      staminaCost: 12,
      accuracy: 0.95,
      range: 1.0,
      executionTime: 600,
      recoveryTime: 900,
      critChance: 0.25,
      critMultiplier: 2.2,
      effects: [],
    },
    {
      id: "li_sidekick",
      name: {
        korean: "옆차기",
        english: "Side Kick",
        romanized: "yeop-chagi",
      },
      koreanName: "옆차기",
      englishName: "Side Kick",
      romanized: "yeop-chagi",
      description: {
        korean: "태권도 옆차기로 늑골이나 무릎을 정확히 타격",
        english: "Taekwondo side kick precisely targeting ribs or knee",
      },
      stance: TrigramStance.LI,
      type: CombatAttackType.KICK,
      damageType: DamageType.BLUNT,
      damage: 34,
      kiCost: 20,
      staminaCost: 24,
      accuracy: 0.88,
      range: 1.6,
      executionTime: 750,
      recoveryTime: 1050,
      critChance: 0.18,
      critMultiplier: 1.9,
      effects: [],
    },
    {
      id: "li_pressure_point",
      name: {
        korean: "혈도공격",
        english: "Pressure Point Attack",
        romanized: "hyeoldo-gonggyeok",
      },
      koreanName: "혈도공격",
      englishName: "Pressure Point Attack",
      romanized: "hyeoldo-gonggyeok",
      description: {
        korean: "급소를 정확히 타격하여 기를 차단",
        english: "Precise vital point strike disrupting ki flow",
      },
      stance: TrigramStance.LI,
      type: CombatAttackType.PRESSURE_POINT,
      damageType: DamageType.PRESSURE,
      damage: 26,
      kiCost: 25,
      staminaCost: 10,
      accuracy: 0.96,
      range: 0.9,
      executionTime: 550,
      recoveryTime: 850,
      critChance: 0.28,
      critMultiplier: 2.3,
      effects: [],
    },
    {
      id: "li_solar_plexus_strike",
      name: {
        korean: "명치타격",
        english: "Solar Plexus Strike",
        romanized: "myeongchi-tagyeok",
      },
      koreanName: "명치타격",
      englishName: "Solar Plexus Strike",
      romanized: "myeongchi-tagyeok",
      description: {
        korean: "명치를 정확히 타격하여 호흡을 차단",
        english: "Precise strike to solar plexus disrupting breath",
      },
      stance: TrigramStance.LI,
      type: CombatAttackType.THRUST,
      damageType: DamageType.INTERNAL,
      damage: 30,
      kiCost: 18,
      staminaCost: 16,
      accuracy: 0.90,
      range: 1.1,
      executionTime: 680,
      recoveryTime: 980,
      critChance: 0.20,
      critMultiplier: 2.0,
      effects: [],
    },
  ],
  // ============= ☳ 진 (JIN) - THUNDER: Explosive Power (Taekwondo Jumping Attacks) =============
  [TrigramStance.JIN]: [
    {
      id: "jin_lightning_flash",
      name: {
        korean: "벽력일섬",
        english: "Lightning Flash",
        romanized: "byeokryeok_ilseom",
      },
      koreanName: "벽력일섬",
      englishName: "Lightning Flash",
      romanized: "byeokryeok_ilseom",
      description: {
        korean: "번개처럼 빠른 일격",
        english: "Swift strike like lightning",
      },
      stance: TrigramStance.JIN,
      type: CombatAttackType.STRIKE,
      damageType: DamageType.BLUNT,
      damage: 28,
      kiCost: 10,
      staminaCost: 25,
      accuracy: 0.75,
      range: 1.0,
      executionTime: 500,
      recoveryTime: 800,
      critChance: 0.12,
      critMultiplier: 1.6,
      effects: [],
    },
    {
      id: "jin_jumping_front_kick",
      name: {
        korean: "뛰어앞차기",
        english: "Jumping Front Kick",
        romanized: "ttwi-eo-ap-chagi",
      },
      koreanName: "뛰어앞차기",
      englishName: "Jumping Front Kick",
      romanized: "ttwi-eo-ap-chagi",
      description: {
        korean: "공중에서 가하는 폭발적인 앞차기",
        english: "Explosive jumping front kick from the air",
      },
      stance: TrigramStance.JIN,
      type: CombatAttackType.KICK,
      damageType: DamageType.IMPACT,
      damage: 36,
      kiCost: 24,
      staminaCost: 32,
      accuracy: 0.72,
      range: 2.0,
      executionTime: 950,
      recoveryTime: 1350,
      critChance: 0.22,
      critMultiplier: 2.1,
      effects: [],
    },
    {
      id: "jin_tornado_kick",
      name: {
        korean: "회오리차기",
        english: "Tornado Kick",
        romanized: "hoe-ori-chagi",
      },
      koreanName: "회오리차기",
      englishName: "Tornado Kick",
      romanized: "hoe-ori-chagi",
      description: {
        korean: "360도 회전하며 가하는 폭발적인 발차기",
        english: "Explosive 360-degree spinning kick",
      },
      stance: TrigramStance.JIN,
      type: CombatAttackType.KICK,
      damageType: DamageType.IMPACT,
      damage: 40,
      kiCost: 28,
      staminaCost: 35,
      accuracy: 0.68,
      range: 2.2,
      executionTime: 1100,
      recoveryTime: 1500,
      critChance: 0.25,
      critMultiplier: 2.3,
      effects: [],
    },
    {
      id: "jin_flying_sidekick",
      name: {
        korean: "날아차기",
        english: "Flying Sidekick",
        romanized: "nal-a-chagi",
      },
      koreanName: "날아차기",
      englishName: "Flying Sidekick",
      romanized: "nal-a-chagi",
      description: {
        korean: "공중에서 가하는 강력한 옆차기",
        english: "Powerful flying sidekick from the air",
      },
      stance: TrigramStance.JIN,
      type: CombatAttackType.KICK,
      damageType: DamageType.IMPACT,
      damage: 38,
      kiCost: 26,
      staminaCost: 34,
      accuracy: 0.70,
      range: 2.4,
      executionTime: 1050,
      recoveryTime: 1450,
      critChance: 0.24,
      critMultiplier: 2.2,
      effects: [],
    },
    {
      id: "jin_back_kick",
      name: {
        korean: "뒤차기",
        english: "Back Kick",
        romanized: "dwi-chagi",
      },
      koreanName: "뒤차기",
      englishName: "Back Kick",
      romanized: "dwi-chagi",
      description: {
        korean: "뒤로 회전하며 가하는 강력한 뒤차기",
        english: "Powerful spinning back kick",
      },
      stance: TrigramStance.JIN,
      type: CombatAttackType.KICK,
      damageType: DamageType.IMPACT,
      damage: 37,
      kiCost: 22,
      staminaCost: 30,
      accuracy: 0.74,
      range: 1.8,
      executionTime: 850,
      recoveryTime: 1250,
      critChance: 0.20,
      critMultiplier: 2.0,
      effects: [],
    },
    {
      id: "jin_knee_strike",
      name: {
        korean: "무릎치기",
        english: "Knee Strike",
        romanized: "mureup-chigi",
      },
      koreanName: "무릎치기",
      englishName: "Knee Strike",
      romanized: "mureup-chigi",
      description: {
        korean: "폭발적인 무릎 공격으로 복부나 얼굴을 타격",
        english: "Explosive knee strike to abdomen or face",
      },
      stance: TrigramStance.JIN,
      type: CombatAttackType.KNEE,
      damageType: DamageType.BLUNT,
      damage: 35,
      kiCost: 20,
      staminaCost: 28,
      accuracy: 0.80,
      range: 0.9,
      executionTime: 600,
      recoveryTime: 1000,
      critChance: 0.18,
      critMultiplier: 1.9,
      effects: [],
    },
  ],
  // ============= ☴ 손 (SON) - WIND: Continuous Pressure (Taekyon Rhythmic Attacks) =============
  [TrigramStance.SON]: [
    {
      id: "son_whirlwind_barrage",
      name: {
        korean: "선풍연격",
        english: "Whirlwind Barrage",
        romanized: "seonpung_yeongyeok",
      },
      koreanName: "선풍연격",
      englishName: "Whirlwind Barrage",
      romanized: "seonpung_yeongyeok",
      description: {
        korean: "바람처럼 연속적인 공격",
        english: "Continuous attacks like wind",
      },
      stance: TrigramStance.SON,
      type: CombatAttackType.STRIKE,
      damageType: DamageType.BLUNT,
      damage: 22,
      kiCost: 8,
      staminaCost: 30,
      accuracy: 0.7,
      range: 0.8,
      executionTime: 400,
      recoveryTime: 600,
      critChance: 0.06,
      critMultiplier: 1.2,
      effects: [],
    },
    {
      id: "son_sweeping_low_kick",
      name: {
        korean: "품밟기",
        english: "Sweeping Foot Attack",
        romanized: "pum-balbgi",
      },
      koreanName: "품밟기",
      englishName: "Sweeping Foot Attack",
      romanized: "pum-balbgi",
      description: {
        korean: "택견의 낮은 발차기로 발목을 쓸어 넘어뜨림",
        english: "Taekyon low sweeping kick targeting ankles",
      },
      stance: TrigramStance.SON,
      type: CombatAttackType.KICK,
      damageType: DamageType.BLUNT,
      damage: 20,
      kiCost: 10,
      staminaCost: 22,
      accuracy: 0.82,
      range: 1.2,
      executionTime: 550,
      recoveryTime: 850,
      critChance: 0.12,
      critMultiplier: 1.4,
      effects: [],
    },
    {
      id: "son_rhythmic_strikes",
      name: {
        korean: "결련수",
        english: "Rhythmic Hand Strikes",
        romanized: "gyeolryeon-su",
      },
      koreanName: "결련수",
      englishName: "Rhythmic Hand Strikes",
      romanized: "gyeolryeon-su",
      description: {
        korean: "택견의 리듬감 있는 연속 손타격",
        english: "Taekyon rhythmic continuous hand strikes",
      },
      stance: TrigramStance.SON,
      type: CombatAttackType.STRIKE,
      damageType: DamageType.BLUNT,
      damage: 24,
      kiCost: 12,
      staminaCost: 28,
      accuracy: 0.78,
      range: 1.0,
      executionTime: 450,
      recoveryTime: 700,
      critChance: 0.08,
      critMultiplier: 1.3,
      effects: [],
    },
    {
      id: "son_flowing_push",
      name: {
        korean: "밀기",
        english: "Flowing Push",
        romanized: "mil-gi",
      },
      koreanName: "밀기",
      englishName: "Flowing Push",
      romanized: "mil-gi",
      description: {
        korean: "택견의 밀기로 상대의 균형을 무너뜨림",
        english: "Taekyon push disrupting opponent's balance",
      },
      stance: TrigramStance.SON,
      type: CombatAttackType.STRIKE,
      damageType: DamageType.PRESSURE,
      damage: 18,
      kiCost: 8,
      staminaCost: 20,
      accuracy: 0.85,
      range: 0.9,
      executionTime: 500,
      recoveryTime: 750,
      critChance: 0.10,
      critMultiplier: 1.3,
      effects: [],
    },
    {
      id: "son_spinning_elbow",
      name: {
        korean: "돌개팔꿈치",
        english: "Spinning Elbow",
        romanized: "dolgae-palkkumchi",
      },
      koreanName: "돌개팔꿈치",
      englishName: "Spinning Elbow",
      romanized: "dolgae-palkkumchi",
      description: {
        korean: "회전하며 연속적으로 가하는 팔꿈치 공격",
        english: "Continuous spinning elbow strikes",
      },
      stance: TrigramStance.SON,
      type: CombatAttackType.ELBOW,
      damageType: DamageType.BLUNT,
      damage: 26,
      kiCost: 14,
      staminaCost: 26,
      accuracy: 0.76,
      range: 0.8,
      executionTime: 550,
      recoveryTime: 850,
      critChance: 0.14,
      critMultiplier: 1.5,
      effects: [],
    },
    {
      id: "son_rapid_footwork",
      name: {
        korean: "품밟기연환",
        english: "Rapid Footwork Chain",
        romanized: "pum-balbgi-yeonhwan",
      },
      koreanName: "품밟기연환",
      englishName: "Rapid Footwork Chain",
      romanized: "pum-balbgi-yeonhwan",
      description: {
        korean: "택견의 빠른 발놀림으로 연속 타격",
        english: "Taekyon rapid footwork with continuous strikes",
      },
      stance: TrigramStance.SON,
      type: CombatAttackType.KICK,
      damageType: DamageType.BLUNT,
      damage: 28,
      kiCost: 16,
      staminaCost: 32,
      accuracy: 0.74,
      range: 1.4,
      executionTime: 600,
      recoveryTime: 900,
      critChance: 0.16,
      critMultiplier: 1.6,
      effects: [],
    },
  ],
  // ============= ☵ 감 (GAM) - WATER: Adaptive Flow (Hapkido Redirect & Counter) =============
  [TrigramStance.GAM]: [
    {
      id: "gam_water_counter",
      name: {
        korean: "수류반격",
        english: "Water Counter",
        romanized: "suryu_bangyeok",
      },
      koreanName: "수류반격",
      englishName: "Water Counter",
      romanized: "suryu_bangyeok",
      description: {
        korean: "물의 흐름으로 적의 공격을 받아넘기는 반격",
        english: "Counter-attack that flows like water",
      },
      stance: TrigramStance.GAM,
      type: CombatAttackType.COUNTER_ATTACK,
      damageType: DamageType.BLUNT,
      damage: 32,
      kiCost: 20,
      staminaCost: 12,
      accuracy: 0.85,
      range: 0.9,
      executionTime: 600,
      recoveryTime: 900,
      critChance: 0.18,
      critMultiplier: 1.7,
      effects: [],
    },
    {
      id: "gam_redirect_throw",
      name: {
        korean: "유도던지기",
        english: "Redirect Throw",
        romanized: "yudo-deonjigi",
      },
      koreanName: "유도던지기",
      englishName: "Redirect Throw",
      romanized: "yudo-deonjigi",
      description: {
        korean: "합기도 방향전환으로 상대의 힘을 이용해 던짐",
        english: "Hapkido redirect using opponent's force for throw",
      },
      stance: TrigramStance.GAM,
      type: CombatAttackType.THROW,
      damageType: DamageType.BLUNT,
      damage: 30,
      kiCost: 18,
      staminaCost: 24,
      accuracy: 0.82,
      range: 1.0,
      executionTime: 850,
      recoveryTime: 1200,
      critChance: 0.16,
      critMultiplier: 1.8,
      effects: [],
    },
    {
      id: "gam_flowing_block",
      name: {
        korean: "유수막기",
        english: "Flowing Block",
        romanized: "yusu-makgi",
      },
      koreanName: "유수막기",
      englishName: "Flowing Block",
      romanized: "yusu-makgi",
      description: {
        korean: "물의 흐름처럼 부드럽게 막고 반격",
        english: "Soft flowing block leading to counter",
      },
      stance: TrigramStance.GAM,
      type: CombatAttackType.BLOCK,
      damageType: DamageType.BLUNT,
      damage: 18,
      kiCost: 10,
      staminaCost: 15,
      accuracy: 0.92,
      range: 0.7,
      executionTime: 400,
      recoveryTime: 700,
      critChance: 0.08,
      critMultiplier: 1.3,
      effects: [],
    },
    {
      id: "gam_circular_parry",
      name: {
        korean: "원형받기",
        english: "Circular Parry",
        romanized: "wonhyeong-batgi",
      },
      koreanName: "원형받기",
      englishName: "Circular Parry",
      romanized: "wonhyeong-batgi",
      description: {
        korean: "합기도 원형 움직임으로 공격을 무력화",
        english: "Hapkido circular motion neutralizing attack",
      },
      stance: TrigramStance.GAM,
      type: CombatAttackType.COUNTER_ATTACK,
      damageType: DamageType.PRESSURE,
      damage: 24,
      kiCost: 14,
      staminaCost: 18,
      accuracy: 0.88,
      range: 0.9,
      executionTime: 550,
      recoveryTime: 850,
      critChance: 0.12,
      critMultiplier: 1.5,
      effects: [],
    },
    {
      id: "gam_hip_throw",
      name: {
        korean: "허리던지기",
        english: "Hip Throw",
        romanized: "heori-deonjigi",
      },
      koreanName: "허리던지기",
      englishName: "Hip Throw",
      romanized: "heori-deonjigi",
      description: {
        korean: "합기도 허리 던지기로 상대를 제압",
        english: "Hapkido hip throw for control",
      },
      stance: TrigramStance.GAM,
      type: CombatAttackType.THROW,
      damageType: DamageType.BLUNT,
      damage: 34,
      kiCost: 22,
      staminaCost: 28,
      accuracy: 0.80,
      range: 1.1,
      executionTime: 900,
      recoveryTime: 1300,
      critChance: 0.20,
      critMultiplier: 1.9,
      effects: [],
    },
    {
      id: "gam_wrist_twist_counter",
      name: {
        korean: "손목비틀기반격",
        english: "Wrist Twist Counter",
        romanized: "sonmok-biteulgi-bangyeok",
      },
      koreanName: "손목비틀기반격",
      englishName: "Wrist Twist Counter",
      romanized: "sonmok-biteulgi-bangyeok",
      description: {
        korean: "공격을 받아 손목을 비틀어 반격",
        english: "Counter by catching and twisting wrist",
      },
      stance: TrigramStance.GAM,
      type: CombatAttackType.COUNTER_ATTACK,
      damageType: DamageType.JOINT,
      damage: 28,
      kiCost: 16,
      staminaCost: 20,
      accuracy: 0.86,
      range: 0.8,
      executionTime: 700,
      recoveryTime: 1000,
      critChance: 0.16,
      critMultiplier: 1.7,
      effects: [],
    },
  ],
  // ============= ☶ 간 (GAN) - MOUNTAIN: Immovable Defense (Hapkido Defensive Mastery) =============
  [TrigramStance.GAN]: [
    {
      id: "gan_rock_defense",
      name: {
        korean: "반석방어",
        english: "Rock Defense",
        romanized: "banseok_bangeo",
      },
      koreanName: "반석방어",
      englishName: "Rock Defense",
      romanized: "banseok_bangeo",
      description: {
        korean: "바위처럼 견고한 방어 자세",
        english: "Solid defense like a rock",
      },
      stance: TrigramStance.GAN,
      type: CombatAttackType.BLOCK,
      damageType: DamageType.BLUNT,
      damage: 15,
      kiCost: 5,
      staminaCost: 8,
      accuracy: 0.95,
      range: 0.5,
      executionTime: 300,
      recoveryTime: 500,
      critChance: 0.02,
      critMultiplier: 1.0,
      effects: [],
    },
    {
      id: "gan_immovable_stance",
      name: {
        korean: "부동자세",
        english: "Immovable Stance",
        romanized: "budong-jase",
      },
      koreanName: "부동자세",
      englishName: "Immovable Stance",
      romanized: "budong-jase",
      description: {
        korean: "산처럼 움직이지 않는 견고한 방어 자세",
        english: "Immovable defensive stance like a mountain",
      },
      stance: TrigramStance.GAN,
      type: CombatAttackType.BLOCK,
      damageType: DamageType.BLUNT,
      damage: 12,
      kiCost: 8,
      staminaCost: 10,
      accuracy: 0.98,
      range: 0.5,
      executionTime: 250,
      recoveryTime: 450,
      critChance: 0.04,
      critMultiplier: 1.1,
      effects: [],
    },
    {
      id: "gan_iron_block",
      name: {
        korean: "철벽막기",
        english: "Iron Wall Block",
        romanized: "cheolbyeok-makgi",
      },
      koreanName: "철벽막기",
      englishName: "Iron Wall Block",
      romanized: "cheolbyeok-makgi",
      description: {
        korean: "합기도 강력한 막기로 공격을 완전히 차단",
        english: "Hapkido powerful block completely stopping attack",
      },
      stance: TrigramStance.GAN,
      type: CombatAttackType.BLOCK,
      damageType: DamageType.BLUNT,
      damage: 20,
      kiCost: 12,
      staminaCost: 15,
      accuracy: 0.94,
      range: 0.6,
      executionTime: 400,
      recoveryTime: 650,
      critChance: 0.06,
      critMultiplier: 1.2,
      effects: [],
    },
    {
      id: "gan_counter_strike",
      name: {
        korean: "반격타",
        english: "Counter Strike",
        romanized: "bangyeok-ta",
      },
      koreanName: "반격타",
      englishName: "Counter Strike",
      romanized: "bangyeok-ta",
      description: {
        korean: "방어 후 즉시 가하는 강력한 반격",
        english: "Powerful counter strike immediately after defense",
      },
      stance: TrigramStance.GAN,
      type: CombatAttackType.COUNTER_ATTACK,
      damageType: DamageType.BLUNT,
      damage: 30,
      kiCost: 16,
      staminaCost: 20,
      accuracy: 0.88,
      range: 1.0,
      executionTime: 600,
      recoveryTime: 950,
      critChance: 0.20,
      critMultiplier: 1.9,
      effects: [],
    },
    {
      id: "gan_mountain_stance_lock",
      name: {
        korean: "산세고정",
        english: "Mountain Stance Lock",
        romanized: "sanse-gojeong",
      },
      koreanName: "산세고정",
      englishName: "Mountain Stance Lock",
      romanized: "sanse-gojeong",
      description: {
        korean: "합기도 방어 자세에서 상대를 고정하고 제압",
        english: "Hapkido defensive position locking and controlling opponent",
      },
      stance: TrigramStance.GAN,
      type: CombatAttackType.GRAPPLE,
      damageType: DamageType.JOINT,
      damage: 24,
      kiCost: 14,
      staminaCost: 18,
      accuracy: 0.86,
      range: 0.8,
      executionTime: 750,
      recoveryTime: 1100,
      critChance: 0.14,
      critMultiplier: 1.6,
      effects: [],
    },
    {
      id: "gan_reversal_technique",
      name: {
        korean: "역기술",
        english: "Reversal Technique",
        romanized: "yeok-gisul",
      },
      koreanName: "역기술",
      englishName: "Reversal Technique",
      romanized: "yeok-gisul",
      description: {
        korean: "상대의 공격을 받아 역으로 제압",
        english: "Receiving attack and reversing into control",
      },
      stance: TrigramStance.GAN,
      type: CombatAttackType.COUNTER_ATTACK,
      damageType: DamageType.JOINT,
      damage: 28,
      kiCost: 18,
      staminaCost: 22,
      accuracy: 0.84,
      range: 0.9,
      executionTime: 800,
      recoveryTime: 1200,
      critChance: 0.18,
      critMultiplier: 1.8,
      effects: [],
    },
  ],
  // ============= ☷ 곤 (GON) - EARTH: Grounding & Takedowns (Ssireum/Hapkido Throws) =============
  [TrigramStance.GON]: [
    {
      id: "gon_earth_embrace",
      name: {
        korean: "대지포옹",
        english: "Earth Embrace",
        romanized: "daeji_pooong",
      },
      koreanName: "대지포옹",
      englishName: "Earth Embrace",
      romanized: "daeji_pooong",
      description: {
        korean: "대지의 힘으로 상대를 제압하는 기술",
        english: "Grappling technique using earth's power",
      },
      stance: TrigramStance.GON,
      type: CombatAttackType.GRAPPLE,
      damageType: DamageType.BLUNT,
      damage: 26,
      kiCost: 16,
      staminaCost: 22,
      accuracy: 0.72,
      range: 0.7,
      executionTime: 900,
      recoveryTime: 1300,
      critChance: 0.08,
      critMultiplier: 1.4,
      effects: [],
    },
    {
      id: "gon_leg_sweep",
      name: {
        korean: "다리걸기",
        english: "Leg Sweep",
        romanized: "dari-geolgi",
      },
      koreanName: "다리걸기",
      englishName: "Leg Sweep",
      romanized: "dari-geolgi",
      description: {
        korean: "상대의 다리를 걸어 넘어뜨리는 기술",
        english: "Sweeping opponent's leg for takedown",
      },
      stance: TrigramStance.GON,
      type: CombatAttackType.KICK,
      damageType: DamageType.BLUNT,
      damage: 22,
      kiCost: 12,
      staminaCost: 18,
      accuracy: 0.80,
      range: 1.2,
      executionTime: 650,
      recoveryTime: 950,
      critChance: 0.12,
      critMultiplier: 1.5,
      effects: [],
    },
    {
      id: "gon_ssireum_throw",
      name: {
        korean: "씨름던지기",
        english: "Ssireum Throw",
        romanized: "ssireum-deonjigi",
      },
      koreanName: "씨름던지기",
      englishName: "Ssireum Throw",
      romanized: "ssireum-deonjigi",
      description: {
        korean: "한국 전통 씨름의 던지기 기술",
        english: "Traditional Korean wrestling throw",
      },
      stance: TrigramStance.GON,
      type: CombatAttackType.THROW,
      damageType: DamageType.BLUNT,
      damage: 32,
      kiCost: 20,
      staminaCost: 28,
      accuracy: 0.76,
      range: 0.9,
      executionTime: 850,
      recoveryTime: 1250,
      critChance: 0.16,
      critMultiplier: 1.7,
      effects: [],
    },
    {
      id: "gon_ground_pound",
      name: {
        korean: "대지강타",
        english: "Ground Pound",
        romanized: "daeji-gangta",
      },
      koreanName: "대지강타",
      englishName: "Ground Pound",
      romanized: "daeji-gangta",
      description: {
        korean: "상대를 땅에 내리찍는 강력한 던지기",
        english: "Powerful throw slamming opponent to ground",
      },
      stance: TrigramStance.GON,
      type: CombatAttackType.THROW,
      damageType: DamageType.CRUSHING,
      damage: 36,
      kiCost: 24,
      staminaCost: 32,
      accuracy: 0.72,
      range: 1.0,
      executionTime: 1000,
      recoveryTime: 1400,
      critChance: 0.20,
      critMultiplier: 2.0,
      effects: [],
    },
    {
      id: "gon_ankle_pick",
      name: {
        korean: "발목잡기",
        english: "Ankle Pick",
        romanized: "balmok-japgi",
      },
      koreanName: "발목잡기",
      englishName: "Ankle Pick",
      romanized: "balmok-japgi",
      description: {
        korean: "발목을 잡아 상대를 넘어뜨리는 기술",
        english: "Grabbing ankle to take opponent down",
      },
      stance: TrigramStance.GON,
      type: CombatAttackType.GRAPPLE,
      damageType: DamageType.BLUNT,
      damage: 24,
      kiCost: 14,
      staminaCost: 20,
      accuracy: 0.82,
      range: 0.8,
      executionTime: 700,
      recoveryTime: 1000,
      critChance: 0.14,
      critMultiplier: 1.6,
      effects: [],
    },
    {
      id: "gon_body_lock_takedown",
      name: {
        korean: "몸통잡기넘어뜨리기",
        english: "Body Lock Takedown",
        romanized: "momtong-japgi-neomeotteurigi",
      },
      koreanName: "몸통잡기넘어뜨리기",
      englishName: "Body Lock Takedown",
      romanized: "momtong-japgi-neomeotteurigi",
      description: {
        korean: "몸통을 감싸 잡고 넘어뜨리는 씨름 기술",
        english: "Ssireum technique grabbing torso for takedown",
      },
      stance: TrigramStance.GON,
      type: CombatAttackType.GRAPPLE,
      damageType: DamageType.BLUNT,
      damage: 28,
      kiCost: 18,
      staminaCost: 24,
      accuracy: 0.78,
      range: 0.9,
      executionTime: 800,
      recoveryTime: 1150,
      critChance: 0.16,
      critMultiplier: 1.7,
      effects: [],
    },
    {
      id: "gon_sacrifice_throw",
      name: {
        korean: "희생던지기",
        english: "Sacrifice Throw",
        romanized: "huisaeng-deonjigi",
      },
      koreanName: "희생던지기",
      englishName: "Sacrifice Throw",
      romanized: "huisaeng-deonjigi",
      description: {
        korean: "자신을 희생하여 상대를 크게 던지는 기술",
        english: "Sacrificing position to execute large throw",
      },
      stance: TrigramStance.GON,
      type: CombatAttackType.THROW,
      damageType: DamageType.BLUNT,
      damage: 34,
      kiCost: 22,
      staminaCost: 30,
      accuracy: 0.74,
      range: 1.1,
      executionTime: 950,
      recoveryTime: 1350,
      critChance: 0.18,
      critMultiplier: 1.9,
      effects: [],
    },
  ],
};

// Technique effectiveness modifiers
export const TECHNIQUE_MODIFIERS = {
  DAMAGE_VARIANCE: 0.15, // ±15% damage variance
  CRITICAL_DAMAGE_BASE: 1.5,
  VITAL_POINT_BONUS: 2.0,
  STANCE_MISMATCH_PENALTY: 0.8,
  COMBO_MULTIPLIER: 1.1,
} as const;

// Complete TECHNIQUE_PROPERTIES with proper enum usage
export const TECHNIQUE_PROPERTIES: Record<
  CombatAttackType, // Fix: Use CombatAttackType instead of string literals
  {
    baseDamage: number;
    range: number;
    accuracy: number;
    kiCost: number;
    staminaCost: number;
  }
> = {
  [CombatAttackType.STRIKE]: {
    baseDamage: 20,
    range: 1.0,
    accuracy: 0.85,
    kiCost: 15,
    staminaCost: 10,
  },
  [CombatAttackType.THRUST]: {
    baseDamage: 25,
    range: 1.5,
    accuracy: 0.9,
    kiCost: 18,
    staminaCost: 12,
  },
  [CombatAttackType.BLOCK]: {
    baseDamage: 5,
    range: 0.5,
    accuracy: 0.95,
    kiCost: 8,
    staminaCost: 15,
  },
  [CombatAttackType.COUNTER_ATTACK]: {
    baseDamage: 22,
    range: 1.0,
    accuracy: 0.88,
    kiCost: 20,
    staminaCost: 15,
  },
  [CombatAttackType.THROW]: {
    baseDamage: 30,
    range: 0.8,
    accuracy: 0.75,
    kiCost: 25,
    staminaCost: 20,
  },
  [CombatAttackType.GRAPPLE]: {
    baseDamage: 15,
    range: 0.6,
    accuracy: 0.8,
    kiCost: 20,
    staminaCost: 25,
  },
  [CombatAttackType.PRESSURE_POINT]: {
    baseDamage: 12,
    range: 0.8,
    accuracy: 0.95,
    kiCost: 25,
    staminaCost: 8,
  },
  [CombatAttackType.NERVE_STRIKE]: {
    baseDamage: 18,
    range: 1.0,
    accuracy: 0.9,
    kiCost: 22,
    staminaCost: 12,
  },
  [CombatAttackType.PUNCH]: {
    baseDamage: 18,
    range: 1.2,
    accuracy: 0.88,
    kiCost: 12,
    staminaCost: 8,
  },
  // Fix: Add missing CombatAttackType properties
  [CombatAttackType.KICK]: {
    baseDamage: 22,
    range: 1.8,
    accuracy: 0.82,
    kiCost: 16,
    staminaCost: 14,
  },
  [CombatAttackType.ELBOW]: {
    baseDamage: 26,
    range: 0.9,
    accuracy: 0.86,
    kiCost: 18,
    staminaCost: 12,
  },
  [CombatAttackType.KNEE]: {
    baseDamage: 28,
    range: 0.7,
    accuracy: 0.84,
    kiCost: 20,
    staminaCost: 16,
  },
} as const;

// Complete DAMAGE_TYPE_EFFECTIVENESS matrix with ALL damage types
export const DAMAGE_TYPE_EFFECTIVENESS: Record<
  DamageType,
  Record<string, number>
> = {
  blunt: {
    bone: 1.3,
    muscle: 1.1,
    organ: 1.0,
    nerve: 0.8,
    vascular: 0.9,
    joint: 1.2,
  },
  piercing: {
    bone: 0.7,
    muscle: 1.2,
    organ: 1.4,
    nerve: 1.1,
    vascular: 1.5,
    joint: 0.8,
  },
  slashing: {
    bone: 0.5,
    muscle: 1.3,
    organ: 1.1,
    nerve: 0.9,
    vascular: 1.4,
    joint: 0.7,
  },
  pressure: {
    bone: 0.6,
    muscle: 0.9,
    organ: 1.1,
    nerve: 1.6,
    vascular: 1.3,
    joint: 1.0,
  },
  nerve: {
    bone: 0.4,
    muscle: 0.8,
    organ: 1.0,
    nerve: 1.8,
    vascular: 1.2,
    joint: 0.9,
  },
  joint: {
    bone: 1.1,
    muscle: 0.9,
    organ: 0.7,
    nerve: 0.8,
    vascular: 0.6,
    joint: 1.7,
  },
  internal: {
    bone: 0.3,
    muscle: 0.7,
    organ: 1.5,
    nerve: 1.3,
    vascular: 1.1,
    joint: 0.5,
  },
  impact: {
    bone: 1.2,
    muscle: 1.0,
    organ: 1.1,
    nerve: 0.9,
    vascular: 0.8,
    joint: 1.3,
  },
  crushing: {
    bone: 1.5,
    muscle: 1.2,
    organ: 1.3,
    nerve: 0.7,
    vascular: 0.8,
    joint: 1.4,
  },
  sharp: {
    bone: 0.6,
    muscle: 1.4,
    organ: 1.2,
    nerve: 1.0,
    vascular: 1.6,
    joint: 0.8,
  },
  electric: {
    bone: 0.2,
    muscle: 1.0,
    organ: 0.9,
    nerve: 2.0,
    vascular: 1.1,
    joint: 0.5,
  },
  fire: {
    bone: 0.3,
    muscle: 1.1,
    organ: 1.2,
    nerve: 1.4,
    vascular: 1.0,
    joint: 0.6,
  },
  ice: {
    bone: 0.4,
    muscle: 0.8,
    organ: 0.9,
    nerve: 1.2,
    vascular: 0.7,
    joint: 1.1,
  },
  poison: {
    bone: 0.1,
    muscle: 0.6,
    organ: 1.8,
    nerve: 1.5,
    vascular: 1.7,
    joint: 0.3,
  },
  psychic: {
    bone: 0.0,
    muscle: 0.2,
    organ: 0.5,
    nerve: 2.2,
    vascular: 0.4,
    joint: 0.1,
  },
  blood: {
    bone: 0.2,
    muscle: 0.8,
    organ: 1.0,
    nerve: 0.5,
    vascular: 2.0,
    joint: 0.3,
  },
} as const;

// Korean technique naming convention (한국 무술 명명법)
export const TECHNIQUE_NAMING = {
  prefixes: {
    heaven: "천", // Heaven/Sky
    earth: "지", // Earth
    human: "인", // Human
    wind: "풍", // Wind
    thunder: "뇌", // Thunder
    fire: "화", // Fire
    water: "수", // Water
    mountain: "산", // Mountain
  },
  suffixes: {
    strike: "격", // Strike/Hit
    thrust: "찌르기", // Thrust/Stab
    block: "막기", // Block/Defend
    throw: "던지기", // Throw
    technique: "술", // Technique/Art
    method: "법", // Method/Way
  },
} as const;

// Korean martial arts technique categories (한국 무술 기법 분류)
export const KOREAN_TECHNIQUE_CATEGORIES = {
  striking: {
    korean: "타격술",
    english: "Striking Techniques",
    subcategories: ["punch", "kick", "elbow", "knee", "palm"],
  },
  grappling: {
    korean: "잡기술",
    english: "Grappling Techniques",
    subcategories: ["throw", "takedown", "joint_lock", "choke"],
  },
  pressure_point: {
    korean: "혈도술",
    english: "Pressure Point Techniques",
    subcategories: ["nerve_strike", "blood_flow", "ki_disruption"],
  },
  defensive: {
    korean: "방어술",
    english: "Defensive Techniques",
    subcategories: ["block", "parry", "dodge", "counter"],
  },
} as const;

// Korean technique difficulty progression (한국 무술 난이도 체계)
export const TECHNIQUE_DIFFICULTY_LEVELS = {
  basic: {
    korean: "기초",
    english: "Basic",
    requirements: { ki: 10, stamina: 8, experience: 0 },
  },
  intermediate: {
    korean: "중급",
    english: "Intermediate",
    requirements: { ki: 20, stamina: 15, experience: 100 },
  },
  advanced: {
    korean: "고급",
    english: "Advanced",
    requirements: { ki: 35, stamina: 25, experience: 500 },
  },
  master: {
    korean: "사범",
    english: "Master",
    requirements: { ki: 50, stamina: 40, experience: 1000 },
  },
} as const;

// ============= 🌑 DARK OPS UNIT TECHNIQUES (암흑작전부대 기술) =============
// Korean Special Operations Dark Ops techniques for 암살자 (Amsalja) archetype
// Based on 5 specialized Korean Dark Ops units with silent incapacitation focus

/**
 * Dark Ops unit specializations (암흑작전 부대 특화)
 */
export const DARK_OPS_UNITS = {
  DARK_OPERATIONS: "암흑작전부대", // Dark Operations Unit
  SHADOW_COMMANDO: "암흑특공대", // Shadow Commando Brigade
  NIGHTFALL_SQUADRON: "심야작전부대", // Nightfall Infiltration Squadron
  BLACK_OPS_TASK_FORCE: "블랙옵스부대", // Black Ops Task Force
  DEEP_SEA_UNIT: "심해침투부대", // Deep Sea Infiltration Unit
} as const;

/**
 * Dark Ops techniques array - Silent incapacitation and tactical assassination
 * Designed for 암살자 (Amsalja) archetype with +30% effectiveness bonus
 */
export const DARK_OPS_TECHNIQUES: readonly KoreanTechnique[] = [
  // ===== 암흑작전부대 (Dark Operations Unit) - Silent Infiltration =====
  {
    id: "darkops_silent_carotid",
    name: {
      korean: "은밀 경동맥 차단",
      english: "Silent Carotid Strike",
      romanized: "Eunmil Gyeongdongmaek Chadan",
    },
    koreanName: "은밀 경동맥 차단",
    englishName: "Silent Carotid Strike",
    romanized: "Eunmil Gyeongdongmaek Chadan",
    description: {
      korean: "경동맥을 압박하여 소리 없이 실신시킴. 3초 내 무의식 유발. 암흑작전부대의 침투 기술.",
      english: "Silent carotid compression causing unconsciousness within 3 seconds. Dark Operations Unit infiltration technique.",
    },
    stance: TrigramStance.GAM, // Water (adaptive)
    type: CombatAttackType.PRESSURE_POINT,
    damageType: DamageType.PRESSURE,
    damage: 28,
    kiCost: 30,
    staminaCost: 25,
    accuracy: 0.92,
    range: 0.8,
    executionTime: 600,
    recoveryTime: 1000,
    critChance: 0.25,
    critMultiplier: 2.0,
    effects: [],
  },
  {
    id: "darkops_nerve_paralysis",
    name: {
      korean: "신경마비타격",
      english: "Nerve Paralysis Strike",
      romanized: "Singyeong Mabi Tagyeok",
    },
    koreanName: "신경마비타격",
    englishName: "Nerve Paralysis Strike",
    romanized: "Singyeong Mabi Tagyeok",
    description: {
      korean: "신경총을 정밀 타격하여 사지 마비 유발. 블랙옵스 기술 강화.",
      english: "Precise nerve cluster strike causing limb paralysis. Black Ops tech-enhanced technique.",
    },
    stance: TrigramStance.LI, // Fire (precision)
    type: CombatAttackType.NERVE_STRIKE,
    damageType: DamageType.NERVE,
    damage: 26,
    kiCost: 25,
    staminaCost: 20,
    accuracy: 0.95,
    range: 1.0,
    executionTime: 500,
    recoveryTime: 900,
    critChance: 0.30,
    critMultiplier: 2.2,
    effects: [],
  },
  
  // ===== 암흑특공대 (Shadow Commando Brigade) - Demolition Tactics =====
  {
    id: "darkops_liver_disruption",
    name: {
      korean: "간장타격",
      english: "Liver Disruption Strike",
      romanized: "Ganjang Tagyeok",
    },
    koreanName: "간장타격",
    englishName: "Liver Disruption Strike",
    romanized: "Ganjang Tagyeok",
    description: {
      korean: "간을 강타하여 내부 출혈과 급격한 체력 소진 유발. 암흑특공대 폭파 전술.",
      english: "Powerful liver strike causing internal trauma and rapid stamina drain. Shadow Commando explosive tactic.",
    },
    stance: TrigramStance.JIN, // Thunder (explosive power)
    type: CombatAttackType.STRIKE,
    damageType: DamageType.INTERNAL,
    damage: 35,
    kiCost: 28,
    staminaCost: 30,
    accuracy: 0.85,
    range: 1.2,
    executionTime: 700,
    recoveryTime: 1100,
    critChance: 0.22,
    critMultiplier: 2.1,
    effects: [],
  },
  {
    id: "darkops_kidney_strike",
    name: {
      korean: "신장충격",
      english: "Kidney Shock",
      romanized: "Sinjang Chunggyeok",
    },
    koreanName: "신장충격",
    englishName: "Kidney Shock",
    romanized: "Sinjang Chunggyeok",
    description: {
      korean: "신장을 타격하여 극심한 고통과 일시적 마비 유발. 폭발적 힘의 암흑특공대 기술.",
      english: "Kidney strike causing severe pain and temporary paralysis. Shadow Commando explosive force technique.",
    },
    stance: TrigramStance.JIN, // Thunder (explosive)
    type: CombatAttackType.STRIKE,
    damageType: DamageType.INTERNAL,
    damage: 33,
    kiCost: 26,
    staminaCost: 28,
    accuracy: 0.82,
    range: 1.1,
    executionTime: 650,
    recoveryTime: 1050,
    critChance: 0.20,
    critMultiplier: 2.0,
    effects: [],
  },
  
  // ===== 심야작전부대 (Nightfall Squadron) - Night Operations =====
  {
    id: "darkops_throat_strike",
    name: {
      korean: "후두차단",
      english: "Throat Disruption",
      romanized: "Hudu Chadan",
    },
    koreanName: "후두차단",
    englishName: "Throat Disruption",
    romanized: "Hudu Chadan",
    description: {
      korean: "후두를 타격하여 호흡 곤란과 발성 불가 유발. 심야작전부대의 무음 제압술.",
      english: "Throat strike causing breathing difficulty and voice loss. Nightfall Squadron silent suppression technique.",
    },
    stance: TrigramStance.SON, // Wind (continuous pressure)
    type: CombatAttackType.STRIKE,
    damageType: DamageType.PRESSURE,
    damage: 30,
    kiCost: 24,
    staminaCost: 22,
    accuracy: 0.88,
    range: 0.9,
    executionTime: 550,
    recoveryTime: 950,
    critChance: 0.24,
    critMultiplier: 2.1,
    effects: [],
  },
  {
    id: "darkops_solar_plexus_paralyze",
    name: {
      korean: "명치마비",
      english: "Solar Plexus Paralysis",
      romanized: "Myeongchi Mabi",
    },
    koreanName: "명치마비",
    englishName: "Solar Plexus Paralysis",
    romanized: "Myeongchi Mabi",
    description: {
      korean: "명치를 정밀 타격하여 횡격막 마비와 호흡 정지. 심야작전부대 야간 전술.",
      english: "Precise solar plexus strike causing diaphragm paralysis and breath cessation. Nightfall Squadron night tactic.",
    },
    stance: TrigramStance.LI, // Fire (precision)
    type: CombatAttackType.THRUST,
    damageType: DamageType.NERVE,
    damage: 32,
    kiCost: 28,
    staminaCost: 24,
    accuracy: 0.90,
    range: 1.0,
    executionTime: 600,
    recoveryTime: 1000,
    critChance: 0.26,
    critMultiplier: 2.2,
    effects: [],
  },
  
  // ===== 블랙옵스부대 (Black Ops Task Force) - Cyber-Enhanced Combat =====
  {
    id: "darkops_brachial_plexus_strike",
    name: {
      korean: "상완신경타격",
      english: "Brachial Plexus Strike",
      romanized: "Sangwan Singyeong Tagyeok",
    },
    koreanName: "상완신경타격",
    englishName: "Brachial Plexus Strike",
    romanized: "Sangwan Singyeong Tagyeok",
    description: {
      korean: "상완 신경총을 타격하여 팔 전체 마비. 블랙옵스 사이버 분석 기반 정밀 타격.",
      english: "Brachial plexus strike causing complete arm paralysis. Black Ops cyber-analysis precision targeting.",
    },
    stance: TrigramStance.LI, // Fire (precision)
    type: CombatAttackType.NERVE_STRIKE,
    damageType: DamageType.NERVE,
    damage: 28,
    kiCost: 26,
    staminaCost: 20,
    accuracy: 0.94,
    range: 1.1,
    executionTime: 550,
    recoveryTime: 900,
    critChance: 0.28,
    critMultiplier: 2.3,
    effects: [],
  },
  {
    id: "darkops_femoral_nerve_strike",
    name: {
      korean: "대퇴신경타격",
      english: "Femoral Nerve Strike",
      romanized: "Daetoe Singyeong Tagyeok",
    },
    koreanName: "대퇴신경타격",
    englishName: "Femoral Nerve Strike",
    romanized: "Daetoe Singyeong Tagyeok",
    description: {
      korean: "대퇴 신경을 타격하여 다리 이동 불가. 블랙옵스 디지털 표적 지정.",
      english: "Femoral nerve strike disabling leg mobility. Black Ops digital targeting system.",
    },
    stance: TrigramStance.LI, // Fire (precision)
    type: CombatAttackType.KICK,
    damageType: DamageType.NERVE,
    damage: 30,
    kiCost: 24,
    staminaCost: 26,
    accuracy: 0.90,
    range: 1.4,
    executionTime: 600,
    recoveryTime: 1000,
    critChance: 0.24,
    critMultiplier: 2.1,
    effects: [],
  },
  
  // ===== 심해침투부대 (Deep Sea Unit) - Amphibious Combat =====
  {
    id: "darkops_rear_choke",
    name: {
      korean: "후방목졸임",
      english: "Rear Naked Choke",
      romanized: "Hubang Mokjorim",
    },
    koreanName: "후방목졸임",
    englishName: "Rear Naked Choke",
    romanized: "Hubang Mokjorim",
    description: {
      korean: "후방에서 목을 조여 혈류 차단과 의식 상실. 심해침투부대 수중 전투 기술.",
      english: "Rear choke cutting blood flow and causing unconsciousness. Deep Sea Unit underwater combat technique.",
    },
    stance: TrigramStance.GAM, // Water (adaptive)
    type: CombatAttackType.GRAPPLE,
    damageType: DamageType.PRESSURE,
    damage: 34,
    kiCost: 30,
    staminaCost: 32,
    accuracy: 0.86,
    range: 0.7,
    executionTime: 800,
    recoveryTime: 1200,
    critChance: 0.22,
    critMultiplier: 2.0,
    effects: [],
  },
  {
    id: "darkops_spinal_strike",
    name: {
      korean: "척추타격",
      english: "Spinal Column Strike",
      romanized: "Cheokchu Tagyeok",
    },
    koreanName: "척추타격",
    englishName: "Spinal Column Strike",
    romanized: "Cheokchu Tagyeok",
    description: {
      korean: "척추를 타격하여 전신 마비와 의식 상실. 심해침투부대 치명적 기술.",
      english: "Spinal column strike causing full-body paralysis and unconsciousness. Deep Sea Unit lethal technique.",
    },
    stance: TrigramStance.GEON, // Heaven (direct force)
    type: CombatAttackType.STRIKE,
    damageType: DamageType.NERVE,
    damage: 40,
    kiCost: 35,
    staminaCost: 35,
    accuracy: 0.78,
    range: 1.0,
    executionTime: 750,
    recoveryTime: 1150,
    critChance: 0.30,
    critMultiplier: 2.5,
    effects: [],
  },
  
  // ===== Additional Dark Ops Techniques - Mixed Units =====
  {
    id: "darkops_jaw_dislocation",
    name: {
      korean: "턱탈구",
      english: "Jaw Dislocation",
      romanized: "Teok Talgu",
    },
    koreanName: "턱탈구",
    englishName: "Jaw Dislocation",
    romanized: "Teok Talgu",
    description: {
      korean: "턱을 비틀어 탈구시키고 의식 혼미. 암흑작전부대 신속 무력화.",
      english: "Twisting jaw causing dislocation and disorientation. Dark Operations rapid incapacitation.",
    },
    stance: TrigramStance.TAE, // Lake (joint manipulation)
    type: CombatAttackType.GRAPPLE,
    damageType: DamageType.JOINT,
    damage: 30,
    kiCost: 22,
    staminaCost: 24,
    accuracy: 0.88,
    range: 0.8,
    executionTime: 600,
    recoveryTime: 1000,
    critChance: 0.24,
    critMultiplier: 2.0,
    effects: [],
  },
  {
    id: "darkops_temple_strike",
    name: {
      korean: "관자놀이급타",
      english: "Temple Knockout Strike",
      romanized: "Gwanja-nori Geubta",
    },
    koreanName: "관자놀이급타",
    englishName: "Temple Knockout Strike",
    romanized: "Gwanja-nori Geubta",
    description: {
      korean: "관자놀이를 정확히 타격하여 즉시 의식 상실. 블랙옵스 치명 타격.",
      english: "Precise temple strike causing immediate unconsciousness. Black Ops lethal targeting.",
    },
    stance: TrigramStance.LI, // Fire (precision)
    type: CombatAttackType.STRIKE,
    damageType: DamageType.BLUNT,
    damage: 38,
    kiCost: 32,
    staminaCost: 28,
    accuracy: 0.92,
    range: 1.1,
    executionTime: 550,
    recoveryTime: 950,
    critChance: 0.32,
    critMultiplier: 2.4,
    effects: [],
  },
  {
    id: "darkops_achilles_sever",
    name: {
      korean: "아킬레스절단",
      english: "Achilles Tendon Sever",
      romanized: "Akilles Jeoldan",
    },
    koreanName: "아킬레스절단",
    englishName: "Achilles Tendon Sever",
    romanized: "Akilles Jeoldan",
    description: {
      korean: "아킬레스건을 공격하여 이동 불가. 암흑특공대 무력화 기술.",
      english: "Achilles tendon strike disabling mobility. Shadow Commando incapacitation technique.",
    },
    stance: TrigramStance.GON, // Earth (ground techniques)
    type: CombatAttackType.KICK,
    damageType: DamageType.SLASHING,
    damage: 32,
    kiCost: 26,
    staminaCost: 28,
    accuracy: 0.84,
    range: 1.3,
    executionTime: 650,
    recoveryTime: 1050,
    critChance: 0.26,
    critMultiplier: 2.2,
    effects: [],
  },
  {
    id: "darkops_ear_strike",
    name: {
      korean: "귓바퀴타격",
      english: "Ear Box Strike",
      romanized: "Gwitbakwi Tagyeok",
    },
    koreanName: "귓바퀴타격",
    englishName: "Ear Box Strike",
    romanized: "Gwitbakwi Tagyeok",
    description: {
      korean: "양쪽 귀를 동시 타격하여 고막 파열과 평형 상실. 심야작전부대 방향 감각 교란.",
      english: "Simultaneous ear strikes rupturing eardrums and disrupting balance. Nightfall Squadron disorientation tactic.",
    },
    stance: TrigramStance.SON, // Wind (continuous pressure)
    type: CombatAttackType.STRIKE,
    damageType: DamageType.BLUNT,
    damage: 28,
    kiCost: 24,
    staminaCost: 22,
    accuracy: 0.86,
    range: 0.9,
    executionTime: 500,
    recoveryTime: 900,
    critChance: 0.22,
    critMultiplier: 2.0,
    effects: [],
  },
  {
    id: "darkops_eye_gouge",
    name: {
      korean: "안구공격",
      english: "Eye Strike",
      romanized: "Angu Gonggyeok",
    },
    koreanName: "안구공격",
    englishName: "Eye Strike",
    romanized: "Angu Gonggyeok",
    description: {
      korean: "눈을 정밀 공격하여 시각 상실과 전투 무력화. 암살자 특화 치명 기술.",
      english: "Precise eye strike causing vision loss and combat incapacitation. Assassin specialty lethal technique.",
    },
    stance: TrigramStance.LI, // Fire (precision)
    type: CombatAttackType.THRUST,
    damageType: DamageType.PIERCING,
    damage: 36,
    kiCost: 30,
    staminaCost: 26,
    accuracy: 0.90,
    range: 1.0,
    executionTime: 500,
    recoveryTime: 900,
    critChance: 0.30,
    critMultiplier: 2.4,
    effects: [],
  },
] as const;

/**
 * Dark Ops archetype bonus configuration
 * 암살자 (Amsalja) gets +30% effectiveness with all Dark Ops techniques
 */
export const DARK_OPS_ARCHETYPE_BONUSES: Record<PlayerArchetype, number> = {
  [PlayerArchetype.AMSALJA]: 1.3, // +30% for Shadow Assassin archetype
  [PlayerArchetype.JEONGBO_YOWON]: 1.15, // +15% for Intelligence Operative
  [PlayerArchetype.HACKER]: 1.10, // +10% for Cyber Warrior (tech synergy)
  [PlayerArchetype.MUSA]: 0.85, // -15% for Traditional Warrior (dishonorable)
  [PlayerArchetype.JOJIK_POKRYEOKBAE]: 1.05, // +5% for Organized Crime (ruthless)
} as const;

/**
 * Dark Ops night operations bonus
 * Time-of-day effectiveness multiplier (simulated)
 */
export const DARK_OPS_NIGHT_BONUS = {
  night: 1.25, // +25% at night (00:00 - 06:00, 18:00 - 23:59)
  day: 1.0, // Normal during day (06:00 - 18:00)
  twilight: 1.15, // +15% during twilight (05:00 - 07:00, 17:00 - 19:00)
} as const;

/**
 * Dark Ops special effects configuration
 */
export const DARK_OPS_SPECIAL_EFFECTS = {
  silent: {
    korean: "무음 공격",
    english: "Silent Attack",
    description: {
      korean: "적에게 경보를 발생시키지 않음",
      english: "Does not alert enemies",
    },
    noAlert: true,
  },
  paralysis: {
    korean: "마비",
    english: "Paralysis",
    description: {
      korean: "일시적 또는 영구적 사지 마비",
      english: "Temporary or permanent limb paralysis",
    },
    duration: 3000, // 3 seconds
  },
  unconsciousness: {
    korean: "의식 상실",
    english: "Unconsciousness",
    description: {
      korean: "즉시 의식을 잃음",
      english: "Immediate loss of consciousness",
    },
    duration: 5000, // 5 seconds
  },
  breathingDifficulty: {
    korean: "호흡 곤란",
    english: "Breathing Difficulty",
    description: {
      korean: "호흡 재생 -75%",
      english: "Breathing regen -75%",
    },
    staminaRegenPenalty: -0.75,
    duration: 5000, // 5 seconds
  },
  disorientation: {
    korean: "방향 감각 상실",
    english: "Disorientation",
    description: {
      korean: "정확도 -50%",
      english: "Accuracy -50%",
    },
    accuracyPenalty: -0.5,
    duration: 4000, // 4 seconds
  },
} as const;

// Korean trigram technique properties (팔괘 기법 특성)
export const TRIGRAM_TECHNIQUE_PROPERTIES = {
  geon: {
    korean: "건괘",
    english: "Heaven",
    element: "metal",
    nature: "yang",
    combatStyle: "direct_force",
    preferredDamageTypes: ["blunt", "crushing", "impact"],
    philosophy: "정의로운 행동을 통한 압도적 힘",
  },
  tae: {
    korean: "태괘",
    english: "Lake",
    element: "metal",
    nature: "yin",
    combatStyle: "fluid_adaptation",
    preferredDamageTypes: ["pressure", "joint", "nerve"],
    philosophy: "부드러운 지속성이 경직된 저항을 이긴다",
  },
  li: {
    korean: "리괘",
    english: "Fire",
    element: "fire",
    nature: "yang",
    combatStyle: "precision_strikes",
    preferredDamageTypes: ["piercing", "sharp", "fire"],
    philosophy: "외과적 정밀함으로 약점을 조명한다",
  },
  jin: {
    korean: "진괘",
    english: "Thunder",
    element: "wood",
    nature: "yang",
    combatStyle: "explosive_power",
    preferredDamageTypes: ["electric", "impact", "blunt"],
    philosophy: "번개처럼 치고 천둥처럼 움직인다",
  },
  son: {
    korean: "손괘",
    english: "Wind",
    element: "wood",
    nature: "yin",
    combatStyle: "continuous_pressure",
    preferredDamageTypes: ["slashing", "pressure", "nerve"],
    philosophy: "지속적인 부드러운 힘이 모든 방어를 관통한다",
  },
  gam: {
    korean: "감괘",
    english: "Water",
    element: "water",
    nature: "yang",
    combatStyle: "adaptive_flow",
    preferredDamageTypes: ["blood", "poison", "internal"],
    philosophy: "장애물 주위로 흘러 급소를 타격한다",
  },
  gan: {
    korean: "간괘",
    english: "Mountain",
    element: "earth",
    nature: "yang",
    combatStyle: "immovable_defense",
    preferredDamageTypes: ["blunt", "crushing", "internal"],
    philosophy: "정적 속에 무한한 잠재 에너지를 담는다",
  },
  gon: {
    korean: "곤괘",
    english: "Earth",
    element: "earth",
    nature: "yin",
    combatStyle: "supportive_control",
    preferredDamageTypes: ["joint", "pressure", "internal"],
    philosophy: "지원하고 양육하여 승리를 이룬다",
  },
} as const;

// Korean archetype combat specializations (한국 무사 유형별 전투 특화)
export const ARCHETYPE_TECHNIQUE_BONUSES = {
  musa: {
    korean: "무사",
    english: "Traditional Warrior",
    philosophy: "Honor through strength, disciplined combat",
    combatStyle: "Direct confrontation, overwhelming force",
    preferredTrigrams: ["geon", "jin"],
    techniques: {
      관절기법: "Joint manipulation and control",
      급소타격: "Military-taught pressure point targeting",
      제압술: "Honor-based control methods",
    },
    bonuses: {
      damageResistance: 1.2,
      jointTechniques: 1.5,
      militaryDiscipline: 1.3,
      darkOpsEffectiveness: 0.85, // -15% for dishonorable techniques
      // Retaining original fields for compatibility, adjust as needed
      damageBonus: 1.2,
      accuracyBonus: 1.1,
      kiEfficiency: 1.0,
      staminaEfficiency: 1.1,
    },
    preferredTechniques: ["strike", "block", "counter_attack"], // Kept for potential compatibility
  },
  amsalja: {
    korean: "암살자",
    english: "Shadow Assassin",
    philosophy: "Efficiency through invisibility, one perfect strike",
    combatStyle: "Stealth approaches, instant takedowns",
    preferredTrigrams: ["son", "gam", "li"], // Added 'li' for precision
    techniques: {
      무성제압: "Silent takedowns preventing vocal response",
      신경파괴: "Precise neural disruption for stealth",
      호흡차단: "Silent breathing and consciousness targeting",
      암흑작전: "Dark Ops techniques for silent incapacitation",
    },
    bonuses: {
      stealthMultiplier: 1.8,
      oneStrikeKill: 2.0,
      silentMovement: 1.5,
      darkOpsEffectiveness: 1.3, // +30% for Dark Ops techniques
      nightOperationsBonus: 1.25, // +25% at night
      // Retaining original fields for compatibility, adjust as needed
      damageBonus: 1.5,
      accuracyBonus: 1.3,
      kiEfficiency: 1.2,
      staminaEfficiency: 0.9,
    },
    preferredTechniques: ["nerve_strike", "pressure_point", "thrust", "darkops"], // Added 'darkops'
  },
  hacker: {
    korean: "해커",
    english: "Cyber Warrior",
    philosophy: "Information as power, technological advantage",
    combatStyle: "Environmental manipulation, tech-assisted strikes",
    preferredTrigrams: ["li", "tae"],
    techniques: {
      해부학적분석: "Data-driven approach to vital points",
      생체역학파괴: "Tech-enhanced body mechanics understanding",
      체계적제압: "Algorithm-based damage accumulation",
      디지털타격: "Digital targeting systems for Dark Ops",
    },
    bonuses: {
      precisionAnalysis: 1.6,
      environmentalControl: 1.4,
      dataOptimization: 1.3,
      darkOpsEffectiveness: 1.10, // +10% for tech-enhanced Dark Ops
      // Retaining original fields for compatibility, adjust as needed
      damageBonus: 1.1,
      accuracyBonus: 1.4,
      kiEfficiency: 1.3,
      staminaEfficiency: 1.0,
    },
    preferredTechniques: ["pressure_point", "nerve_strike"], // Kept for potential compatibility
  },
  jeongbo_yowon: {
    korean: "정보요원",
    english: "Intelligence Operative",
    philosophy: "Knowledge through observation, strategic thinking",
    combatStyle: "Psychological manipulation, precise timing",
    preferredTrigrams: ["gan", "gon"],
    techniques: {
      고통순응: "Intelligence-based submission through pain",
      심리적압박: "Mental intimidation through technique",
      정보추출: "Combat methods from interrogation training",
      첩보전술: "Espionage tactics and Dark Ops methods",
    },
    bonuses: {
      psychologicalWarfare: 1.5,
      strategicAnalysis: 1.4,
      painCompliance: 1.7,
      darkOpsEffectiveness: 1.15, // +15% for espionage Dark Ops
      // Retaining original fields for compatibility, adjust as needed
      damageBonus: 1.1,
      accuracyBonus: 1.2,
      kiEfficiency: 1.1,
      staminaEfficiency: 1.2,
    },
    preferredTechniques: ["grapple", "pressure_point"], // Kept for potential compatibility
  },
  jojik_pokryeokbae: {
    korean: "조직폭력배",
    english: "Organized Crime",
    philosophy: "Survival through ruthlessness, practical violence",
    combatStyle: "Dirty fighting, improvised weapons",
    preferredTrigrams: ["jin", "gam"],
    techniques: {
      환경활용: "Street-smart use of surroundings as weapons",
      더러운기법: "Brutal eye attacks, groin strikes, hair pulling",
      생존격투: "Underground whatever-it-takes combat",
      무자비술: "Ruthless Dark Ops adaptations",
    },
    bonuses: {
      dirtyFighting: 1.8,
      survivalInstinct: 1.6,
      streetSmart: 1.5,
      darkOpsEffectiveness: 1.05, // +5% for ruthless Dark Ops
      // Retaining original fields for compatibility, adjust as needed
      damageBonus: 1.3,
      accuracyBonus: 0.9,
      kiEfficiency: 0.9,
      staminaEfficiency: 1.3,
    },
    preferredTechniques: ["strike", "throw", "grapple"], // Kept for potential compatibility
  },
} as const;
