/**
 * Post Screenshots to GitHub PR
 * 
 * This script posts screenshot filenames to PR comments with links to
 * workflow artifacts.  Screenshots are preserved as artifacts for 30 days. 
 * 
 * Usage:
 *   GITHUB_TOKEN=xxx PR_NUMBER=123 GITHUB_RUN_ID=456 npx tsx scripts/post-screenshots-to-pr. ts
 */

import * as fs from 'fs';
import * as path from 'path';

const SCREENSHOTS_DIR = path.join(process.cwd(), 'screenshots');
const ARTIFACT_RETENTION_DAYS = 30;

interface GitHubAPIConfig {
  readonly token: string;
  readonly owner: string;
  readonly repo: string;
  readonly prNumber: number;
  readonly runId?: string;
}

interface ScreenshotInfo {
  readonly filename: string;
}

/**
 * Get GitHub API configuration from environment
 */
function getGitHubConfig(): GitHubAPIConfig {
  const token = process.env.GITHUB_TOKEN;
  const prNumber = process.env.PR_NUMBER ??  process.env.GITHUB_PR_NUMBER;
  const runId = process.env.GITHUB_RUN_ID;
  
  if (! token) {
    throw new Error('GITHUB_TOKEN environment variable is required');
  }
  
  if (! prNumber) {
    throw new Error('PR_NUMBER or GITHUB_PR_NUMBER environment variable is required');
  }
  
  if (runId && !/^\d+$/.test(runId)) {
    throw new Error(`Invalid GITHUB_RUN_ID format: "${runId}".  Must be a numeric workflow run ID`);
  }
  
  // Parse owner/repo from GITHUB_REPOSITORY or use defaults
  const repoEnv = process.env.GITHUB_REPOSITORY ??  'Hack23/blacktrigram';
  const parts = repoEnv.split('/');
  if (parts.length !== 2 || !parts[0] || !parts[1]) {
    throw new Error(`Invalid GITHUB_REPOSITORY format: "${repoEnv}".  Expected "owner/repo"`);
  }
  const [owner, repo] = parts;
  
  const parsedPrNumber = parseInt(prNumber, 10);
  if (isNaN(parsedPrNumber) || parsedPrNumber <= 0) {
    throw new Error(`Invalid PR number: "${prNumber}". Must be a positive integer`);
  }
  
  return {
    token,
    owner,
    repo,
    prNumber: parsedPrNumber,
    runId,
  };
}


/**
 * Create PR comment with screenshot list and artifact links
 */
async function createPRComment(
  config: GitHubAPIConfig,
  screenshots: ScreenshotInfo[]
): Promise<void> {
  const { token, owner, repo, prNumber, runId } = config;
  
  console.log('\n📝 Creating PR comment...');
  
  try {
    // Build comment body with screenshot list and artifact links
    let commentBody = `## 📸 Automated UI Screenshots\n\n`;
    
    if (screenshots.length > 0) {
      commentBody += `### 📋 Screenshots Captured (${screenshots.length})\n\n`;
      commentBody += `| # | Screenshot |\n`;
      commentBody += `|---|------------|\n`;
      
      screenshots.forEach((screenshot, index) => {
        const displayName = screenshot.filename.replace('. png', ''). replace(/-/g, ' ');
        commentBody += `| ${index + 1} | \`${screenshot.filename}\` - ${displayName} |\n`;
      });
      
      commentBody += `\n`;
    } else {
      commentBody += `⚠️ No screenshots were captured. Check the workflow logs.\n\n`;
    }
    
    // Add artifact download link
    if (runId) {
      commentBody += `### 📦 Download Screenshots\n\n`;
      commentBody += `📥 **[Download all screenshots from workflow artifacts](https://github.com/${owner}/${repo}/actions/runs/${runId})**\n\n`;
      commentBody += `> Screenshots are preserved as workflow artifacts for ${ARTIFACT_RETENTION_DAYS} days.\n\n`;
    } else {
      commentBody += `> ⚠️ No workflow run ID available. Set \`GITHUB_RUN_ID\` to include artifact download links.\n\n`;
    }
    
    commentBody += `---\n`;
    commentBody += `🤖 *Generated by Playwright automation*\n`;
    
    // Create new comment
    const createUrl = `https://api.github.com/repos/${owner}/${repo}/issues/${prNumber}/comments`;
    
    console.log(`  📍 Creating new comment: ${createUrl}`);
    
    let response;
    try {
      response = await fetch(createUrl, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Accept': 'application/vnd.github. v3+json',
          'Content-Type': 'application/json',
        },
        body: JSON. stringify({
          body: commentBody,
        }),
      });
    } catch (error) {
      const errorMessage = error instanceof Error ?  error.message : String(error);
      throw new Error(`Failed to connect to GitHub API: ${errorMessage}`);
    }
    
    if (!response. ok) {
      const errorText = await response.text();
      throw new Error(`Failed to create comment: ${response.status} ${response.statusText}\n${errorText}`);
    }
    
    const result = await response.json();
    console. log(`  ✅ Comment created: ${result.html_url}`);
    
  } catch (error) {
    console.error('  ❌ Failed to create PR comment:', error);
    throw error;
  }
}


/**
 * Main execution
 */
async function main() {
  console.log('🎮 Black Trigram - Post Screenshots to PR\n');
  
  try {
    // Get GitHub configuration
    const config = getGitHubConfig();
    console.log(`Repository: ${config.owner}/${config.repo}`);
    console.log(`PR Number: #${config.prNumber}`);
    if (config.runId) {
      console.log(`Run ID: ${config.runId}`);
    }
    console.log();
    
    // Check if screenshots directory exists
    if (!fs.existsSync(SCREENSHOTS_DIR)) {
      throw new Error(`Screenshots directory not found: ${SCREENSHOTS_DIR}\nRun capture-screenshots.ts first. `);
    }
    
    // Find all screenshots
    console.log('🔍 Finding screenshots...');
    const screenshotFiles = fs.readdirSync(SCREENSHOTS_DIR)
      .filter(file => file.endsWith('.png'))
      .sort();
    
    console.log(`  ✅ Found ${screenshotFiles. length} screenshots\n`);
    
    const screenshotList: ScreenshotInfo[] = screenshotFiles.map(filename => ({
      filename,
    }));
    
    // Create PR comment with artifact links
    await createPRComment(config, screenshotList);
    
    console.log('\n✅ Successfully posted screenshots to PR! ');
    
  } catch (error) {
    console.error('\n❌ Error:', error);
    process. exit(1);
  }
}

// Run the script
main(). catch(console.error);
