/**
 * Type definitions for vitalpoint types
 * Auto-generated by type migration script
 */

// Vital point system imports from shared types
import type {
  DamageRange,
  KoreanText,
  PlayerArchetype,
  Position,
  TrigramStance,
  VitalPointCategory,
  VitalPointEffectType,
  VitalPointSeverity,
} from "../../types";
import { AnimationType } from "../animation/MartialArtsAnimationBuilder";
import { EffectIntensity } from "../effects";
import { PlayerState } from "../player";
import { StatusEffect } from "../types";
import type { PhysicalReachConfig } from "../../types/physics";

/**
 * Korean Technique - Core martial arts technique definition
 * 한국 무술 기술 정의
 *
 * @korean 한국무술기술
 */
export interface KoreanTechnique {
  /** Unique identifier for the technique */
  id: string;

  /** Bilingual name with romanization */
  name: {
    korean: string;
    english: string;
    romanized: string;
  };

  /** Korean name (한글) */
  koreanName: string;
  /** English name */
  englishName: string;
  /** Romanized Korean (로마자) */
  romanized: string;

  /** Technique description */
  description: {
    korean: string;
    english: string;
  };

  /** Required stance for execution (팔괘 자세) */
  stance: TrigramStance;

  /** Combat attack type (e.g., "strike", "kick", "throw") */
  type: string;
  /** Damage type (e.g., "blunt", "internal", "joint") */
  damageType: string;

  // Combat stats (전투 능력치)
  damage: number;
  kiCost: number;
  staminaCost: number;
  accuracy: number;
  
  /**
   * Physical reach configuration using body parts and attributes.
   * Replaces simple range value with complex calculation based on:
   * - Body part length (arm/leg from archetype physical attributes)
   * - Animation extension multiplier (from hit timing)
   * - Stance modifiers (Eight Trigrams bonuses)
   * 
   * **Korean**: 물리적 도달 설정
   * @korean 물리적도달설정
   */
  reachConfig: PhysicalReachConfig;
  
  executionTime: number;
  recoveryTime: number;
  critChance: number;
  critMultiplier: number;

  /** Status effects applied on hit */
  effects: readonly StatusEffect[];

  /**
   * Animation type for direct mapping to skeletal animation
   * 스켈레탈 애니메이션에 직접 매핑하기 위한 애니메이션 타입
   *
   * @korean 애니메이션타입
   */
  animationType?: AnimationType;

  /**
   * Animation speed modifier (default: 1.0)
   * 애니메이션 속도 조절 (기본: 1.0)
   */
  animationSpeed?: number;
}

/**
 * Korean text with romanization for vital point names
 */
export interface VitalPointNames {
  readonly korean: string;
  readonly english: string;
  readonly romanized: string;
}

/**
 * Unified VitalPoint interface matching actual usage
 */
export interface VitalPoint {
  readonly id: string;
  readonly names: VitalPointNames; // ✅ Fixed: Use 'names' structure
  readonly position: Position;
  readonly category: VitalPointCategory;
  readonly severity: VitalPointSeverity;
  readonly baseDamage?: number;
  readonly effects: readonly VitalPointEffect[];
  readonly description: KoreanText;
  readonly targetingDifficulty: number;
  readonly effectiveStances: readonly TrigramStance[];

  // Optional properties for backwards compatibility
  readonly korean?: KoreanText;
  readonly english?: string;
  readonly anatomicalName?: string;
  readonly radius?: number; // Make optional with default
  readonly damage?: DamageRange;
  readonly difficulty?: number;
  readonly requiredForce?: number; // Make optional with default
  readonly safetyWarning?: string;
  readonly location?: Position;
  readonly region?: string;
}

/**
 * Result of a vital point hit calculation
 * Unified to resolve property name conflicts and includes meridian effects
 */
export interface VitalPointHitResult {
  /** Whether the vital point was successfully hit */
  readonly hit: boolean;

  /** The vital point that was hit (primary property name) */
  readonly vitalPointHit?: VitalPoint;

  /** Legacy property name for backwards compatibility */
  readonly vitalPoint?: VitalPoint;

  /** Base damage from the vital point hit */
  readonly damage: number;

  /** Status effects applied by the vital point hit */
  readonly effects: readonly StatusEffect[];

  /** Severity level of the vital point hit */
  readonly severity: VitalPointSeverity;

  /** Accuracy of the hit (0-1) */
  readonly accuracy?: number;

  /** Additional multiplier applied to damage */
  readonly multiplier?: number;

  /** Meridian flow multiplier based on time of day (0.7-1.3) */
  readonly meridianMultiplier?: number;

  /** Status effects from meridian disruption */
  readonly meridianEffects?: readonly StatusEffect[];
}

export interface VitalPointEffect {
  readonly id: string;
  readonly type: VitalPointEffectType;
  readonly intensity: EffectIntensity;
  readonly duration: number;
  readonly description: KoreanText;
  readonly stackable: boolean;
  readonly source?: string;
}

export interface DamageResult {
  readonly damage: number;
  readonly effects: readonly StatusEffect[];
  readonly isCritical: boolean;
  readonly isVitalPoint: boolean;
}

export interface AnatomicalRegion {
  readonly id: string;
  readonly name: KoreanText;
  readonly boundaries: readonly Position[];
  readonly vitalPoints: readonly VitalPoint[];
}

export interface BodyRegionData {
  readonly id: string;
  readonly name: KoreanText;
  readonly boundaries: readonly Position[];
  readonly vitalPoints: readonly VitalPoint[];
}

export interface VitalPointSystemConfig {
  readonly precisionRequired: number;
  readonly damageMultipliers: Record<string, number>;
  readonly effectDurations: Record<string, number>;
}

export interface VitalPointSystemInterface {
  processHit: (
    targetPosition: Position,
    technique: KoreanTechnique,
    baseDamage: number,
    attackerArchetype: PlayerArchetype,
    targetDimensions: { width: number; height: number },
    targetedVitalPointId?: string | null
  ) => VitalPointHitResult;
  calculateHit: (
    technique: KoreanTechnique,
    targetVitalPointId: string | null,
    accuracyRoll: number,
    attackerPosition: Position,
    defenderPosition: Position,
    defenderStance: TrigramStance
  ) => VitalPointHitResult;
  applyVitalPointEffects: (
    player: PlayerState,
    vitalPoint: VitalPoint,
    intensityMultiplier?: number
  ) => PlayerState;
}

export interface VitalPointSystem {
  readonly getVitalPoints: () => readonly VitalPoint[];
  readonly checkHit: (position: Position, force: number) => VitalPointHitResult;
  readonly calculateDamage: (vitalPoint: VitalPoint, force: number) => number;
}

// Define VitalPoint locally to avoid circular import
export interface VitalPoint {
  readonly id: string;
  readonly names: {
    readonly korean: string;
    readonly english: string;
    readonly romanized: string;
  };
  readonly position: Position;
  readonly category: VitalPointCategory;
  readonly severity: VitalPointSeverity;
  readonly baseDamage?: number;
  readonly effects: readonly VitalPointEffect[];
  readonly description: KoreanText;
  readonly targetingDifficulty: number;
  readonly effectiveStances: readonly TrigramStance[];
}

export interface VitalPointEffect {
  readonly id: string;
  readonly type: VitalPointEffectType;
  readonly intensity: EffectIntensity;
  readonly duration: number;
  readonly description: KoreanText;
  readonly stackable: boolean;
  readonly source?: string;
}

// Region data
export interface RegionData {
  readonly name: KoreanText;
  readonly boundaries: readonly Position[];
  readonly vitalPoints: readonly VitalPoint[];
  readonly vulnerabilities: readonly string[];
}
