/**
 * Comprehensive Korean Vital Points Database (급소 데이터베이스)
 * 
 * **Korean**: 한국 무술 급소 시스템
 * 
 * Contains all 70 Korean martial arts vital points (급소) based on traditional
 * martial arts knowledge and anatomical targeting. Points are organized by
 * body region and categorized by physiological system affected.
 * 
 * @module systems/vitalpoint/VitalPointsData
 * @category Vital Point System
 * @korean 급소데이터
 */

import { VitalPointCategory, VitalPointSeverity, BodyRegion, TrigramStance, VitalPointEffectType } from "@/types";
import { EffectIntensity } from "../effects";
import { VitalPoint } from "./types";

/**
 * Complete database of 70 Korean vital points organized by body region.
 * 
 * **Korean**: 70개 급소 데이터베이스
 * 
 * Distribution:
 * - Head: 12 points
 * - Torso: 24 points
 * - Arms: 17 points (각 8-9 per arm)
 * - Legs: 17 points (각 8-9 per leg)
 * 
 * @public
 * @korean 급소데이터베이스
 */
export const VITAL_POINTS_DATA: readonly VitalPoint[] = [
  // ============= HEAD REGION (12 points) =============
  {
    id: "head_temple",
    names: {
      korean: "태양혈",
      english: "Temple",
      romanized: "taeyang-hyeol",
    },
    position: { x: 100, y: 50 },
    category: VitalPointCategory.NEUROLOGICAL,
    severity: VitalPointSeverity.CRITICAL,
    baseDamage: 35,
    effects: [
      {
        id: "stun_major",
        type: VitalPointEffectType.STUN,
        intensity: EffectIntensity.HIGH,
        duration: 3000,
        description: { korean: "심각한 기절", english: "Severe stunning" },
        stackable: false,
      },
    ],
    description: {
      korean: "관자놀이의 압박점, 뇌진탕 위험",
      english: "Pressure point at temple, concussion risk",
      romanized: "gwanja-nori-ui apbakjeom",
    },
    targetingDifficulty: 0.7,
    effectiveStances: [TrigramStance.LI, TrigramStance.JIN],
  },
  {
    id: "head_jaw",
    names: {
      korean: "턱끝",
      english: "Jaw Point",
      romanized: "teok-kkeut",
    },
    position: { x: 105, y: 80 },
    category: VitalPointCategory.NEUROLOGICAL,
    severity: VitalPointSeverity.MAJOR,
    baseDamage: 30,
    effects: [],
    description: {
      korean: "턱 끝 타격으로 뇌진탕 유발",
      english: "Jaw strike causes concussion",
      romanized: "teok-kkeut tagyeok",
    },
    targetingDifficulty: 0.6,
    effectiveStances: [TrigramStance.GEON, TrigramStance.JIN],
  },
  {
    id: "head_nose",
    names: {
      korean: "코",
      english: "Nose Bridge",
      romanized: "ko",
    },
    position: { x: 102, y: 65 },
    category: VitalPointCategory.SKELETAL,
    severity: VitalPointSeverity.MAJOR,
    baseDamage: 28,
    effects: [],
    description: {
      korean: "코뼈 골절, 시야 방해",
      english: "Nasal bone fracture, vision impairment",
      romanized: "koppyeo goljeol",
    },
    targetingDifficulty: 0.5,
    effectiveStances: [TrigramStance.LI, TrigramStance.GEON],
  },
  {
    id: "head_eye",
    names: {
      korean: "눈",
      english: "Eye",
      romanized: "nun",
    },
    position: { x: 98, y: 55 },
    category: VitalPointCategory.ORGAN,
    severity: VitalPointSeverity.CRITICAL,
    baseDamage: 40,
    effects: [],
    description: {
      korean: "눈 공격, 실명 위험",
      english: "Eye strike, blindness risk",
      romanized: "nun gonggyeok",
    },
    targetingDifficulty: 0.8,
    effectiveStances: [TrigramStance.LI],
  },
  {
    id: "head_ear",
    names: {
      korean: "귀",
      english: "Ear",
      romanized: "gwi",
    },
    position: { x: 90, y: 60 },
    category: VitalPointCategory.ORGAN,
    severity: VitalPointSeverity.MODERATE,
    baseDamage: 22,
    effects: [
      {
        id: "balance_loss",
        type: VitalPointEffectType.DISORIENTATION,
        intensity: EffectIntensity.MEDIUM,
        duration: 2500,
        description: { korean: "평형 감각 상실 및 청력 손상", english: "Balance and hearing impairment" },
        stackable: false,
      },
    ],
    description: {
      korean: "고막 손상, 평형 감각 상실",
      english: "Eardrum damage, balance loss",
      romanized: "gomak sonsang",
    },
    targetingDifficulty: 0.6,
    effectiveStances: [TrigramStance.GEON],
  },
  {
    id: "head_back_skull",
    names: {
      korean: "뒤통수",
      english: "Back of Skull",
      romanized: "dwi-tongsu",
    },
    position: { x: 80, y: 50 },
    category: VitalPointCategory.NEUROLOGICAL,
    severity: VitalPointSeverity.LETHAL,
    baseDamage: 50,
    effects: [
      {
        id: "unconsciousness",
        type: VitalPointEffectType.STUN,
        intensity: EffectIntensity.EXTREME,
        duration: 10000,
        description: { korean: "즉각적 무의식", english: "Instant unconsciousness" },
        stackable: false,
      },
    ],
    description: {
      korean: "뇌간 손상, 즉각적 무의식",
      english: "Brainstem damage, instant unconsciousness",
      romanized: "noegan sonsang",
    },
    targetingDifficulty: 0.7,
    effectiveStances: [TrigramStance.JIN, TrigramStance.GEON],
  },
  {
    id: "head_crown",
    names: {
      korean: "정수리",
      english: "Crown",
      romanized: "jeongsu-ri",
    },
    position: { x: 100, y: 30 },
    category: VitalPointCategory.NEUROLOGICAL,
    severity: VitalPointSeverity.CRITICAL,
    baseDamage: 38,
    effects: [],
    description: {
      korean: "두개골 타격, 뇌 손상",
      english: "Skull impact, brain damage",
      romanized: "dugaegol tagyeok",
    },
    targetingDifficulty: 0.8,
    effectiveStances: [TrigramStance.GEON],
  },
  {
    id: "head_philtrum",
    names: {
      korean: "인중",
      english: "Philtrum",
      romanized: "injung",
    },
    position: { x: 102, y: 70 },
    category: VitalPointCategory.NEUROLOGICAL,
    severity: VitalPointSeverity.MODERATE,
    baseDamage: 25,
    effects: [],
    description: {
      korean: "인중 타격, 통증 및 기절",
      english: "Philtrum strike, pain and stunning",
      romanized: "injung tagyeok",
    },
    targetingDifficulty: 0.6,
    effectiveStances: [TrigramStance.LI],
  },
  {
    id: "head_side_neck",
    names: {
      korean: "목옆",
      english: "Side Neck",
      romanized: "mog-yeop",
    },
    position: { x: 92, y: 85 },
    category: VitalPointCategory.VASCULAR,
    severity: VitalPointSeverity.CRITICAL,
    baseDamage: 42,
    effects: [
      {
        id: "unconsciousness_carotid",
        type: VitalPointEffectType.UNCONSCIOUSNESS,
        intensity: EffectIntensity.HIGH,
        duration: 8000,
        description: { korean: "경동맥 압박으로 실신", english: "Carotid compression unconsciousness" },
        stackable: false,
      },
    ],
    description: {
      korean: "경동맥 압박, 실신 유발",
      english: "Carotid compression, unconsciousness",
      romanized: "gyeongdongmaek apbak",
    },
    targetingDifficulty: 0.7,
    effectiveStances: [TrigramStance.SON, TrigramStance.GAM],
  },
  {
    id: "head_throat",
    names: {
      korean: "목",
      english: "Throat",
      romanized: "mok",
    },
    position: { x: 102, y: 90 },
    category: VitalPointCategory.RESPIRATORY,
    severity: VitalPointSeverity.LETHAL,
    baseDamage: 55,
    effects: [
      {
        id: "breathing_difficulty",
        type: VitalPointEffectType.BREATHLESSNESS,
        intensity: EffectIntensity.EXTREME,
        duration: 5000,
        description: { korean: "호흡 곤란", english: "Severe breathing difficulty" },
        stackable: false,
      },
    ],
    description: {
      korean: "기도 폐쇄, 호흡 곤란",
      english: "Airway closure, breathing difficulty",
      romanized: "gido pyeshwe",
    },
    targetingDifficulty: 0.8,
    effectiveStances: [TrigramStance.LI],
  },
  {
    id: "head_mastoid",
    names: {
      korean: "유양돌기",
      english: "Mastoid Process",
      romanized: "yuyang-dolgi",
    },
    position: { x: 88, y: 75 },
    category: VitalPointCategory.NEUROLOGICAL,
    severity: VitalPointSeverity.MAJOR,
    baseDamage: 32,
    effects: [],
    description: {
      korean: "귀 뒤 돌기, 평형 감각 손상",
      english: "Behind ear protrusion, balance disruption",
      romanized: "gwi dwi dolgi",
    },
    targetingDifficulty: 0.7,
    effectiveStances: [TrigramStance.LI, TrigramStance.GEON],
  },
  {
    id: "head_chin",
    names: {
      korean: "턱",
      english: "Chin",
      romanized: "teok",
    },
    position: { x: 102, y: 82 },
    category: VitalPointCategory.NEUROLOGICAL,
    severity: VitalPointSeverity.MAJOR,
    baseDamage: 30,
    effects: [],
    description: {
      korean: "턱 중앙 타격, 뇌진탕",
      english: "Chin center strike, concussion",
      romanized: "teok jungang tagyeok",
    },
    targetingDifficulty: 0.5,
    effectiveStances: [TrigramStance.GEON, TrigramStance.JIN],
  },

  // ============= TORSO REGION (24 points) =============
  {
    id: "torso_solar_plexus",
    names: {
      korean: "명치",
      english: "Solar Plexus",
      romanized: "myeongchi",
    },
    position: { x: 102, y: 140 },
    category: VitalPointCategory.NEUROLOGICAL,
    severity: VitalPointSeverity.CRITICAL,
    baseDamage: 40,
    effects: [
      {
        id: "breath_knocked_out",
        type: VitalPointEffectType.BREATHLESSNESS,
        intensity: EffectIntensity.HIGH,
        duration: 3000,
        description: { korean: "호흡 곤란 및 신경 충격", english: "Breathing difficulty and nerve shock" },
        stackable: false,
      },
    ],
    description: {
      korean: "신경총 타격, 호흡 곤란",
      english: "Nerve plexus strike, breathing difficulty",
      romanized: "singyeongjong tagyeok",
    },
    targetingDifficulty: 0.6,
    effectiveStances: [TrigramStance.JIN, TrigramStance.GEON],
  },
  {
    id: "torso_heart",
    names: {
      korean: "심장",
      english: "Heart Region",
      romanized: "simjang",
    },
    position: { x: 98, y: 130 },
    category: VitalPointCategory.ORGAN,
    severity: VitalPointSeverity.LETHAL,
    baseDamage: 60,
    effects: [
      {
        id: "cardiac_disruption",
        type: VitalPointEffectType.ORGAN_DISRUPTION,
        intensity: EffectIntensity.EXTREME,
        duration: 10000,
        description: { korean: "심장 충격", english: "Cardiac disruption" },
        stackable: false,
      },
    ],
    description: {
      korean: "심장 충격, 심정지 위험",
      english: "Heart shock, cardiac arrest risk",
      romanized: "simjang chunggyeok",
    },
    targetingDifficulty: 0.9,
    effectiveStances: [TrigramStance.JIN, TrigramStance.LI],
  },
  {
    id: "torso_liver",
    names: {
      korean: "간",
      english: "Liver",
      romanized: "gan",
    },
    position: { x: 110, y: 145 },
    category: VitalPointCategory.ORGAN,
    severity: VitalPointSeverity.CRITICAL,
    baseDamage: 45,
    effects: [
      {
        id: "internal_bleeding",
        type: VitalPointEffectType.ORGAN_DISRUPTION,
        intensity: EffectIntensity.HIGH,
        duration: 8000,
        description: { korean: "내출혈 및 극심한 통증", english: "Internal bleeding and severe pain" },
        stackable: false,
      },
      {
        id: "liver_pain",
        type: VitalPointEffectType.PAIN,
        intensity: EffectIntensity.HIGH,
        duration: 6000,
        description: { korean: "간 타격 통증", english: "Liver strike pain" },
        stackable: false,
      },
    ],
    description: {
      korean: "간 손상, 내출혈",
      english: "Liver damage, internal bleeding",
      romanized: "gan sonsang",
    },
    targetingDifficulty: 0.7,
    effectiveStances: [TrigramStance.GEON, TrigramStance.JIN],
  },
  {
    id: "torso_spleen",
    names: {
      korean: "비장",
      english: "Spleen",
      romanized: "bijang",
    },
    position: { x: 94, y: 145 },
    category: VitalPointCategory.ORGAN,
    severity: VitalPointSeverity.CRITICAL,
    baseDamage: 45,
    effects: [
      {
        id: "spleen_rupture_risk",
        type: VitalPointEffectType.ORGAN_DISRUPTION,
        intensity: EffectIntensity.HIGH,
        duration: 8000,
        description: { korean: "비장 파열 위험", english: "Spleen rupture risk" },
        stackable: false,
      },
      {
        id: "internal_bleeding_spleen",
        type: VitalPointEffectType.WEAKNESS,
        intensity: EffectIntensity.HIGH,
        duration: 10000,
        description: { korean: "내출혈로 인한 약화", english: "Weakness from internal bleeding" },
        stackable: false,
      },
    ],
    description: {
      korean: "비장 파열 위험",
      english: "Spleen rupture risk",
      romanized: "bijang paryeol",
    },
    targetingDifficulty: 0.7,
    effectiveStances: [TrigramStance.GEON, TrigramStance.JIN],
  },
  {
    id: "torso_kidney_left",
    names: {
      korean: "좌신장",
      english: "Left Kidney",
      romanized: "jwa-sinjang",
    },
    position: { x: 94, y: 155 },
    category: VitalPointCategory.ORGAN,
    severity: VitalPointSeverity.MAJOR,
    baseDamage: 38,
    effects: [],
    description: {
      korean: "신장 타격, 심한 통증",
      english: "Kidney strike, severe pain",
      romanized: "sinjang tagyeok",
    },
    targetingDifficulty: 0.6,
    effectiveStances: [TrigramStance.GEON, TrigramStance.SON],
  },
  {
    id: "torso_kidney_right",
    names: {
      korean: "우신장",
      english: "Right Kidney",
      romanized: "u-sinjang",
    },
    position: { x: 110, y: 155 },
    category: VitalPointCategory.ORGAN,
    severity: VitalPointSeverity.MAJOR,
    baseDamage: 38,
    effects: [],
    description: {
      korean: "신장 타격, 심한 통증",
      english: "Kidney strike, severe pain",
      romanized: "sinjang tagyeok",
    },
    targetingDifficulty: 0.6,
    effectiveStances: [TrigramStance.GEON, TrigramStance.SON],
  },
  {
    id: "torso_ribs_floating",
    names: {
      korean: "갈비뼈",
      english: "Floating Ribs",
      romanized: "galbi-ppyeo",
    },
    position: { x: 106, y: 150 },
    category: VitalPointCategory.SKELETAL,
    severity: VitalPointSeverity.MAJOR,
    baseDamage: 35,
    effects: [],
    description: {
      korean: "늑골 골절, 내장 손상",
      english: "Rib fracture, organ damage",
      romanized: "neukgol goljeol",
    },
    targetingDifficulty: 0.5,
    effectiveStances: [TrigramStance.GEON, TrigramStance.SON],
  },
  {
    id: "torso_sternum",
    names: {
      korean: "흉골",
      english: "Sternum",
      romanized: "hyunggol",
    },
    position: { x: 102, y: 130 },
    category: VitalPointCategory.SKELETAL,
    severity: VitalPointSeverity.CRITICAL,
    baseDamage: 40,
    effects: [],
    description: {
      korean: "흉골 골절, 심장 압박",
      english: "Sternum fracture, heart compression",
      romanized: "hyunggol goljeol",
    },
    targetingDifficulty: 0.6,
    effectiveStances: [TrigramStance.GEON, TrigramStance.JIN],
  },
  {
    id: "torso_spine_upper",
    names: {
      korean: "상부척추",
      english: "Upper Spine",
      romanized: "sangbu-cheokchu",
    },
    position: { x: 80, y: 120 },
    category: VitalPointCategory.NEUROLOGICAL,
    severity: VitalPointSeverity.LETHAL,
    baseDamage: 55,
    effects: [],
    description: {
      korean: "척추 손상, 마비 위험",
      english: "Spine damage, paralysis risk",
      romanized: "cheokchu sonsang",
    },
    targetingDifficulty: 0.8,
    effectiveStances: [TrigramStance.GEON, TrigramStance.GON],
  },
  {
    id: "torso_spine_mid",
    names: {
      korean: "중부척추",
      english: "Mid Spine",
      romanized: "jungbu-cheokchu",
    },
    position: { x: 80, y: 145 },
    category: VitalPointCategory.NEUROLOGICAL,
    severity: VitalPointSeverity.CRITICAL,
    baseDamage: 42,
    effects: [],
    description: {
      korean: "척추 타격, 신경 손상",
      english: "Spine strike, nerve damage",
      romanized: "cheokchu tagyeok",
    },
    targetingDifficulty: 0.7,
    effectiveStances: [TrigramStance.GEON, TrigramStance.GON],
  },
  {
    id: "torso_groin",
    names: {
      korean: "사타구니",
      english: "Groin",
      romanized: "sata-guni",
    },
    position: { x: 102, y: 170 },
    category: VitalPointCategory.NEUROLOGICAL,
    severity: VitalPointSeverity.CRITICAL,
    baseDamage: 50,
    effects: [
      {
        id: "extreme_pain",
        type: VitalPointEffectType.PAIN,
        intensity: EffectIntensity.EXTREME,
        duration: 5000,
        description: { korean: "극심한 통증", english: "Extreme pain" },
        stackable: false,
      },
      {
        id: "groin_stun",
        type: VitalPointEffectType.STUN,
        intensity: EffectIntensity.HIGH,
        duration: 3000,
        description: { korean: "충격으로 인한 기절", english: "Shock-induced incapacitation" },
        stackable: false,
      },
    ],
    description: {
      korean: "사타구니 타격, 극심한 통증",
      english: "Groin strike, extreme pain",
      romanized: "sata-guni tagyeok",
    },
    targetingDifficulty: 0.7,
    effectiveStances: [TrigramStance.LI, TrigramStance.GEON],
  },
  {
    id: "torso_bladder",
    names: {
      korean: "방광",
      english: "Bladder",
      romanized: "banggwang",
    },
    position: { x: 102, y: 165 },
    category: VitalPointCategory.ORGAN,
    severity: VitalPointSeverity.MAJOR,
    baseDamage: 35,
    effects: [],
    description: {
      korean: "방광 압박, 통증 및 기능 장애",
      english: "Bladder compression, pain and dysfunction",
      romanized: "banggwang apbak",
    },
    targetingDifficulty: 0.6,
    effectiveStances: [TrigramStance.GEON, TrigramStance.SON],
  },
  // Additional torso points (continuing to 24 total)
  {
    id: "torso_collarbone_left",
    names: {
      korean: "좌쇄골",
      english: "Left Collarbone",
      romanized: "jwa-swaegol",
    },
    position: { x: 92, y: 110 },
    category: VitalPointCategory.SKELETAL,
    severity: VitalPointSeverity.MAJOR,
    baseDamage: 32,
    effects: [],
    description: {
      korean: "쇄골 골절, 팔 움직임 제한",
      english: "Collarbone fracture, arm movement limitation",
      romanized: "swaegol goljeol",
    },
    targetingDifficulty: 0.6,
    effectiveStances: [TrigramStance.GEON, TrigramStance.JIN],
  },
  {
    id: "torso_collarbone_right",
    names: {
      korean: "우쇄골",
      english: "Right Collarbone",
      romanized: "u-swaegol",
    },
    position: { x: 112, y: 110 },
    category: VitalPointCategory.SKELETAL,
    severity: VitalPointSeverity.MAJOR,
    baseDamage: 32,
    effects: [],
    description: {
      korean: "쇄골 골절, 팔 움직임 제한",
      english: "Collarbone fracture, arm movement limitation",
      romanized: "swaegol goljeol",
    },
    targetingDifficulty: 0.6,
    effectiveStances: [TrigramStance.GEON, TrigramStance.JIN],
  },
  {
    id: "torso_armpit_nerve",
    names: {
      korean: "겨드랑이신경",
      english: "Armpit Nerve",
      romanized: "gyeodeu-rangi singyeong",
    },
    position: { x: 85, y: 120 },
    category: VitalPointCategory.NEUROLOGICAL,
    severity: VitalPointSeverity.MODERATE,
    baseDamage: 28,
    effects: [],
    description: {
      korean: "신경총 타격, 팔 마비",
      english: "Nerve plexus strike, arm paralysis",
      romanized: "singyeongjong tagyeok",
    },
    targetingDifficulty: 0.7,
    effectiveStances: [TrigramStance.LI, TrigramStance.SON],
  },
  {
    id: "torso_abs_center",
    names: {
      korean: "복부중앙",
      english: "Abdominal Center",
      romanized: "bokbu-jungang",
    },
    position: { x: 102, y: 148 },
    category: VitalPointCategory.MUSCULAR,
    severity: VitalPointSeverity.MODERATE,
    baseDamage: 26,
    effects: [],
    description: {
      korean: "복근 손상, 호흡 곤란",
      english: "Abdominal muscle damage, breathing difficulty",
      romanized: "bokgeun sonsang",
    },
    targetingDifficulty: 0.5,
    effectiveStances: [TrigramStance.GEON, TrigramStance.SON],
  },
  {
    id: "torso_diaphragm",
    names: {
      korean: "횡격막",
      english: "Diaphragm",
      romanized: "hyeokgyeongmak",
    },
    position: { x: 102, y: 142 },
    category: VitalPointCategory.RESPIRATORY,
    severity: VitalPointSeverity.MAJOR,
    baseDamage: 35,
    effects: [],
    description: {
      korean: "횡격막 충격, 호흡 정지",
      english: "Diaphragm shock, breathing cessation",
      romanized: "hyeokgyeongmak chunggyeok",
    },
    targetingDifficulty: 0.7,
    effectiveStances: [TrigramStance.JIN, TrigramStance.GEON],
  },
  {
    id: "torso_lower_back",
    names: {
      korean: "요추",
      english: "Lower Back",
      romanized: "yochu",
    },
    position: { x: 80, y: 160 },
    category: VitalPointCategory.NEUROLOGICAL,
    severity: VitalPointSeverity.MAJOR,
    baseDamage: 36,
    effects: [],
    description: {
      korean: "요추 타격, 다리 통증",
      english: "Lower back strike, leg pain",
      romanized: "yochu tagyeok",
    },
    targetingDifficulty: 0.6,
    effectiveStances: [TrigramStance.GEON, TrigramStance.GON],
  },
  {
    id: "torso_side_ribs_left",
    names: {
      korean: "좌측늑골",
      english: "Left Side Ribs",
      romanized: "jwa-cheuk neukgol",
    },
    position: { x: 90, y: 140 },
    category: VitalPointCategory.SKELETAL,
    severity: VitalPointSeverity.MAJOR,
    baseDamage: 33,
    effects: [],
    description: {
      korean: "늑골 타격, 호흡 곤란",
      english: "Rib strike, breathing difficulty",
      romanized: "neukgol tagyeok",
    },
    targetingDifficulty: 0.5,
    effectiveStances: [TrigramStance.SON, TrigramStance.GEON],
  },
  {
    id: "torso_side_ribs_right",
    names: {
      korean: "우측늑골",
      english: "Right Side Ribs",
      romanized: "u-cheuk neukgol",
    },
    position: { x: 114, y: 140 },
    category: VitalPointCategory.SKELETAL,
    severity: VitalPointSeverity.MAJOR,
    baseDamage: 33,
    effects: [],
    description: {
      korean: "늑골 타격, 호흡 곤란",
      english: "Rib strike, breathing difficulty",
      romanized: "neukgol tagyeok",
    },
    targetingDifficulty: 0.5,
    effectiveStances: [TrigramStance.SON, TrigramStance.GEON],
  },
  {
    id: "torso_navel",
    names: {
      korean: "배꼽",
      english: "Navel",
      romanized: "bae-kkop",
    },
    position: { x: 102, y: 152 },
    category: VitalPointCategory.ORGAN,
    severity: VitalPointSeverity.MODERATE,
    baseDamage: 27,
    effects: [],
    description: {
      korean: "복부 중심 타격",
      english: "Abdominal center strike",
      romanized: "bokbu jungsim tagyeok",
    },
    targetingDifficulty: 0.4,
    effectiveStances: [TrigramStance.GEON, TrigramStance.SON],
  },
  {
    id: "torso_shoulder_blade_left",
    names: {
      korean: "좌견갑골",
      english: "Left Shoulder Blade",
      romanized: "jwa-gyeongapgol",
    },
    position: { x: 75, y: 115 },
    category: VitalPointCategory.SKELETAL,
    severity: VitalPointSeverity.MODERATE,
    baseDamage: 28,
    effects: [],
    description: {
      korean: "견갑골 타격, 팔 기능 저하",
      english: "Shoulder blade strike, arm function reduction",
      romanized: "gyeongapgol tagyeok",
    },
    targetingDifficulty: 0.6,
    effectiveStances: [TrigramStance.GEON, TrigramStance.GON],
  },
  {
    id: "torso_shoulder_blade_right",
    names: {
      korean: "우견갑골",
      english: "Right Shoulder Blade",
      romanized: "u-gyeongapgol",
    },
    position: { x: 129, y: 115 },
    category: VitalPointCategory.SKELETAL,
    severity: VitalPointSeverity.MODERATE,
    baseDamage: 28,
    effects: [],
    description: {
      korean: "견갑골 타격, 팔 기능 저하",
      english: "Shoulder blade strike, arm function reduction",
      romanized: "gyeongapgol tagyeok",
    },
    targetingDifficulty: 0.6,
    effectiveStances: [TrigramStance.GEON, TrigramStance.GON],
  },
  {
    id: "torso_tailbone",
    names: {
      korean: "미골",
      english: "Tailbone",
      romanized: "migol",
    },
    position: { x: 80, y: 170 },
    category: VitalPointCategory.SKELETAL,
    severity: VitalPointSeverity.MAJOR,
    baseDamage: 34,
    effects: [],
    description: {
      korean: "미골 골절, 앉기 곤란",
      english: "Tailbone fracture, sitting difficulty",
      romanized: "migol goljeol",
    },
    targetingDifficulty: 0.7,
    effectiveStances: [TrigramStance.GON, TrigramStance.JIN],
  },

  // ============= LEFT ARM REGION (8 points) =============
  {
    id: "arm_left_shoulder",
    names: {
      korean: "좌어깨",
      english: "Left Shoulder",
      romanized: "jwa-eokkae",
    },
    position: { x: 82, y: 110 },
    category: VitalPointCategory.JOINT,
    severity: VitalPointSeverity.MODERATE,
    baseDamage: 26,
    effects: [],
    description: {
      korean: "어깨 관절 탈구",
      english: "Shoulder joint dislocation",
      romanized: "eokkae gwanjeol talgoo",
    },
    targetingDifficulty: 0.6,
    effectiveStances: [TrigramStance.TAE, TrigramStance.GAM],
  },
  {
    id: "arm_left_bicep",
    names: {
      korean: "좌상완",
      english: "Left Bicep",
      romanized: "jwa-sangwan",
    },
    position: { x: 78, y: 125 },
    category: VitalPointCategory.MUSCULAR,
    severity: VitalPointSeverity.MINOR,
    baseDamage: 18,
    effects: [],
    description: {
      korean: "상완 근육 손상",
      english: "Bicep muscle damage",
      romanized: "sangwan geunnyuk sonsang",
    },
    targetingDifficulty: 0.5,
    effectiveStances: [TrigramStance.GEON, TrigramStance.SON],
  },
  {
    id: "arm_left_elbow",
    names: {
      korean: "좌팔꿈치",
      english: "Left Elbow",
      romanized: "jwa-palkumchi",
    },
    position: { x: 74, y: 142 },
    category: VitalPointCategory.JOINT,
    severity: VitalPointSeverity.MAJOR,
    baseDamage: 30,
    effects: [],
    description: {
      korean: "팔꿈치 골절 또는 탈구",
      english: "Elbow fracture or dislocation",
      romanized: "palkumchi goljeol",
    },
    targetingDifficulty: 0.6,
    effectiveStances: [TrigramStance.TAE, TrigramStance.GON],
  },
  {
    id: "arm_left_forearm",
    names: {
      korean: "좌전완",
      english: "Left Forearm",
      romanized: "jwa-jeonwan",
    },
    position: { x: 72, y: 155 },
    category: VitalPointCategory.SKELETAL,
    severity: VitalPointSeverity.MODERATE,
    baseDamage: 24,
    effects: [],
    description: {
      korean: "전완부 골절",
      english: "Forearm fracture",
      romanized: "jeonwanbu goljeol",
    },
    targetingDifficulty: 0.5,
    effectiveStances: [TrigramStance.GAN],
  },
  {
    id: "arm_left_wrist",
    names: {
      korean: "좌손목",
      english: "Left Wrist",
      romanized: "jwa-sonmok",
    },
    position: { x: 70, y: 168 },
    category: VitalPointCategory.JOINT,
    severity: VitalPointSeverity.MODERATE,
    baseDamage: 22,
    effects: [],
    description: {
      korean: "손목 골절 또는 염좌",
      english: "Wrist fracture or sprain",
      romanized: "sonmok goljeol",
    },
    targetingDifficulty: 0.6,
    effectiveStances: [TrigramStance.TAE, TrigramStance.GAM],
  },
  {
    id: "arm_left_hand",
    names: {
      korean: "좌손등",
      english: "Left Hand",
      romanized: "jwa-sondeung",
    },
    position: { x: 68, y: 178 },
    category: VitalPointCategory.SKELETAL,
    severity: VitalPointSeverity.MINOR,
    baseDamage: 16,
    effects: [],
    description: {
      korean: "손등 타격, 기능 저하",
      english: "Hand strike, function reduction",
      romanized: "sondeung tagyeok",
    },
    targetingDifficulty: 0.5,
    effectiveStances: [TrigramStance.LI],
  },
  {
    id: "arm_left_radial_nerve",
    names: {
      korean: "좌요골신경",
      english: "Left Radial Nerve",
      romanized: "jwa-yogol singyeong",
    },
    position: { x: 72, y: 148 },
    category: VitalPointCategory.NEUROLOGICAL,
    severity: VitalPointSeverity.MODERATE,
    baseDamage: 25,
    effects: [],
    description: {
      korean: "요골 신경 타격, 팔 마비",
      english: "Radial nerve strike, arm paralysis",
      romanized: "yogol singyeong tagyeok",
    },
    targetingDifficulty: 0.7,
    effectiveStances: [TrigramStance.LI, TrigramStance.SON],
  },
  {
    id: "arm_left_ulnar_nerve",
    names: {
      korean: "좌척골신경",
      english: "Left Ulnar Nerve",
      romanized: "jwa-cheokgol singyeong",
    },
    position: { x: 74, y: 150 },
    category: VitalPointCategory.NEUROLOGICAL,
    severity: VitalPointSeverity.MODERATE,
    baseDamage: 24,
    effects: [],
    description: {
      korean: "척골 신경 타격, 손 기능 상실",
      english: "Ulnar nerve strike, hand function loss",
      romanized: "cheokgol singyeong tagyeok",
    },
    targetingDifficulty: 0.7,
    effectiveStances: [TrigramStance.LI],
  },

  // ============= RIGHT ARM REGION (9 points) =============
  {
    id: "arm_right_shoulder",
    names: {
      korean: "우어깨",
      english: "Right Shoulder",
      romanized: "u-eokkae",
    },
    position: { x: 122, y: 110 },
    category: VitalPointCategory.JOINT,
    severity: VitalPointSeverity.MODERATE,
    baseDamage: 26,
    effects: [],
    description: {
      korean: "어깨 관절 탈구",
      english: "Shoulder joint dislocation",
      romanized: "eokkae gwanjeol talgoo",
    },
    targetingDifficulty: 0.6,
    effectiveStances: [TrigramStance.TAE, TrigramStance.GAM],
  },
  {
    id: "arm_right_bicep",
    names: {
      korean: "우상완",
      english: "Right Bicep",
      romanized: "u-sangwan",
    },
    position: { x: 126, y: 125 },
    category: VitalPointCategory.MUSCULAR,
    severity: VitalPointSeverity.MINOR,
    baseDamage: 18,
    effects: [],
    description: {
      korean: "상완 근육 손상",
      english: "Bicep muscle damage",
      romanized: "sangwan geunnyuk sonsang",
    },
    targetingDifficulty: 0.5,
    effectiveStances: [TrigramStance.GEON, TrigramStance.SON],
  },
  {
    id: "arm_right_elbow",
    names: {
      korean: "우팔꿈치",
      english: "Right Elbow",
      romanized: "u-palkumchi",
    },
    position: { x: 130, y: 142 },
    category: VitalPointCategory.JOINT,
    severity: VitalPointSeverity.MAJOR,
    baseDamage: 30,
    effects: [],
    description: {
      korean: "팔꿈치 골절 또는 탈구",
      english: "Elbow fracture or dislocation",
      romanized: "palkumchi goljeol",
    },
    targetingDifficulty: 0.6,
    effectiveStances: [TrigramStance.TAE, TrigramStance.GON],
  },
  {
    id: "arm_right_forearm",
    names: {
      korean: "우전완",
      english: "Right Forearm",
      romanized: "u-jeonwan",
    },
    position: { x: 132, y: 155 },
    category: VitalPointCategory.SKELETAL,
    severity: VitalPointSeverity.MODERATE,
    baseDamage: 24,
    effects: [],
    description: {
      korean: "전완부 골절",
      english: "Forearm fracture",
      romanized: "jeonwanbu goljeol",
    },
    targetingDifficulty: 0.5,
    effectiveStances: [TrigramStance.GAN],
  },
  {
    id: "arm_right_wrist",
    names: {
      korean: "우손목",
      english: "Right Wrist",
      romanized: "u-sonmok",
    },
    position: { x: 134, y: 168 },
    category: VitalPointCategory.JOINT,
    severity: VitalPointSeverity.MODERATE,
    baseDamage: 22,
    effects: [],
    description: {
      korean: "손목 골절 또는 염좌",
      english: "Wrist fracture or sprain",
      romanized: "sonmok goljeol",
    },
    targetingDifficulty: 0.6,
    effectiveStances: [TrigramStance.TAE, TrigramStance.GAM],
  },
  {
    id: "arm_right_hand",
    names: {
      korean: "우손등",
      english: "Right Hand",
      romanized: "u-sondeung",
    },
    position: { x: 136, y: 178 },
    category: VitalPointCategory.SKELETAL,
    severity: VitalPointSeverity.MINOR,
    baseDamage: 16,
    effects: [],
    description: {
      korean: "손등 타격, 기능 저하",
      english: "Hand strike, function reduction",
      romanized: "sondeung tagyeok",
    },
    targetingDifficulty: 0.5,
    effectiveStances: [TrigramStance.LI],
  },
  {
    id: "arm_right_radial_nerve",
    names: {
      korean: "우요골신경",
      english: "Right Radial Nerve",
      romanized: "u-yogol singyeong",
    },
    position: { x: 132, y: 148 },
    category: VitalPointCategory.NEUROLOGICAL,
    severity: VitalPointSeverity.MODERATE,
    baseDamage: 25,
    effects: [],
    description: {
      korean: "요골 신경 타격, 팔 마비",
      english: "Radial nerve strike, arm paralysis",
      romanized: "yogol singyeong tagyeok",
    },
    targetingDifficulty: 0.7,
    effectiveStances: [TrigramStance.LI, TrigramStance.SON],
  },
  {
    id: "arm_right_ulnar_nerve",
    names: {
      korean: "우척골신경",
      english: "Right Ulnar Nerve",
      romanized: "u-cheokgol singyeong",
    },
    position: { x: 130, y: 150 },
    category: VitalPointCategory.NEUROLOGICAL,
    severity: VitalPointSeverity.MODERATE,
    baseDamage: 24,
    effects: [],
    description: {
      korean: "척골 신경 타격, 손 기능 상실",
      english: "Ulnar nerve strike, hand function loss",
      romanized: "cheokgol singyeong tagyeok",
    },
    targetingDifficulty: 0.7,
    effectiveStances: [TrigramStance.LI],
  },
  {
    id: "arm_right_tricep",
    names: {
      korean: "우삼두",
      english: "Right Tricep",
      romanized: "u-samdu",
    },
    position: { x: 128, y: 135 },
    category: VitalPointCategory.MUSCULAR,
    severity: VitalPointSeverity.MINOR,
    baseDamage: 17,
    effects: [],
    description: {
      korean: "삼두근 손상",
      english: "Tricep muscle damage",
      romanized: "samdugeun sonsang",
    },
    targetingDifficulty: 0.5,
    effectiveStances: [TrigramStance.GEON],
  },

  // ============= LEFT LEG REGION (8 points) =============
  {
    id: "leg_left_thigh",
    names: {
      korean: "좌대퇴",
      english: "Left Thigh",
      romanized: "jwa-daetwe",
    },
    position: { x: 94, y: 185 },
    category: VitalPointCategory.MUSCULAR,
    severity: VitalPointSeverity.MODERATE,
    baseDamage: 22,
    effects: [],
    description: {
      korean: "대퇴근 손상, 이동 곤란",
      english: "Thigh muscle damage, movement difficulty",
      romanized: "daetwegeun sonsang",
    },
    targetingDifficulty: 0.5,
    effectiveStances: [TrigramStance.GEON, TrigramStance.SON],
  },
  {
    id: "leg_left_knee",
    names: {
      korean: "좌무릎",
      english: "Left Knee",
      romanized: "jwa-mureup",
    },
    position: { x: 94, y: 205 },
    category: VitalPointCategory.JOINT,
    severity: VitalPointSeverity.CRITICAL,
    baseDamage: 38,
    effects: [],
    description: {
      korean: "무릎 관절 파괴, 보행 불가",
      english: "Knee joint destruction, unable to walk",
      romanized: "mureup gwanjeol pagoe",
    },
    targetingDifficulty: 0.7,
    effectiveStances: [TrigramStance.TAE, TrigramStance.GON],
  },
  {
    id: "leg_left_shin",
    names: {
      korean: "좌정강이",
      english: "Left Shin",
      romanized: "jwa-jeonggang-i",
    },
    position: { x: 94, y: 220 },
    category: VitalPointCategory.SKELETAL,
    severity: VitalPointSeverity.MODERATE,
    baseDamage: 26,
    effects: [],
    description: {
      korean: "정강이 골절",
      english: "Shin fracture",
      romanized: "jeonggang-i goljeol",
    },
    targetingDifficulty: 0.5,
    effectiveStances: [TrigramStance.GEON, TrigramStance.GAN],
  },
  {
    id: "leg_left_ankle",
    names: {
      korean: "좌발목",
      english: "Left Ankle",
      romanized: "jwa-balmok",
    },
    position: { x: 94, y: 235 },
    category: VitalPointCategory.JOINT,
    severity: VitalPointSeverity.MAJOR,
    baseDamage: 28,
    effects: [],
    description: {
      korean: "발목 염좌 또는 골절",
      english: "Ankle sprain or fracture",
      romanized: "balmok yeomjwa",
    },
    targetingDifficulty: 0.6,
    effectiveStances: [TrigramStance.TAE, TrigramStance.GON],
  },
  {
    id: "leg_left_foot",
    names: {
      korean: "좌발등",
      english: "Left Foot",
      romanized: "jwa-baldeung",
    },
    position: { x: 94, y: 245 },
    category: VitalPointCategory.SKELETAL,
    severity: VitalPointSeverity.MINOR,
    baseDamage: 18,
    effects: [],
    description: {
      korean: "발등 골절, 보행 곤란",
      english: "Foot fracture, walking difficulty",
      romanized: "baldeung goljeol",
    },
    targetingDifficulty: 0.5,
    effectiveStances: [TrigramStance.GON],
  },
  {
    id: "leg_left_calf",
    names: {
      korean: "좌종아리",
      english: "Left Calf",
      romanized: "jwa-jong-ari",
    },
    position: { x: 92, y: 225 },
    category: VitalPointCategory.MUSCULAR,
    severity: VitalPointSeverity.MODERATE,
    baseDamage: 23,
    effects: [],
    description: {
      korean: "종아리 근육 손상",
      english: "Calf muscle damage",
      romanized: "jong-ari geunnyuk sonsang",
    },
    targetingDifficulty: 0.5,
    effectiveStances: [TrigramStance.SON, TrigramStance.GEON],
  },
  {
    id: "leg_left_achilles",
    names: {
      korean: "좌아킬레스건",
      english: "Left Achilles Tendon",
      romanized: "jwa-akilleseugeon",
    },
    position: { x: 90, y: 238 },
    category: VitalPointCategory.MUSCULAR,
    severity: VitalPointSeverity.CRITICAL,
    baseDamage: 40,
    effects: [],
    description: {
      korean: "아킬레스건 파열, 이동 불가",
      english: "Achilles tendon rupture, cannot move",
      romanized: "akilleseugeon paryeol",
    },
    targetingDifficulty: 0.8,
    effectiveStances: [TrigramStance.LI, TrigramStance.GON],
  },
  {
    id: "leg_left_femoral_nerve",
    names: {
      korean: "좌대퇴신경",
      english: "Left Femoral Nerve",
      romanized: "jwa-daetwe singyeong",
    },
    position: { x: 96, y: 180 },
    category: VitalPointCategory.NEUROLOGICAL,
    severity: VitalPointSeverity.MAJOR,
    baseDamage: 32,
    effects: [],
    description: {
      korean: "대퇴 신경 타격, 다리 마비",
      english: "Femoral nerve strike, leg paralysis",
      romanized: "daetwe singyeong tagyeok",
    },
    targetingDifficulty: 0.7,
    effectiveStances: [TrigramStance.LI, TrigramStance.SON],
  },

  // ============= RIGHT LEG REGION (9 points) =============
  {
    id: "leg_right_thigh",
    names: {
      korean: "우대퇴",
      english: "Right Thigh",
      romanized: "u-daetwe",
    },
    position: { x: 110, y: 185 },
    category: VitalPointCategory.MUSCULAR,
    severity: VitalPointSeverity.MODERATE,
    baseDamage: 22,
    effects: [],
    description: {
      korean: "대퇴근 손상, 이동 곤란",
      english: "Thigh muscle damage, movement difficulty",
      romanized: "daetwegeun sonsang",
    },
    targetingDifficulty: 0.5,
    effectiveStances: [TrigramStance.GEON, TrigramStance.SON],
  },
  {
    id: "leg_right_knee",
    names: {
      korean: "우무릎",
      english: "Right Knee",
      romanized: "u-mureup",
    },
    position: { x: 110, y: 205 },
    category: VitalPointCategory.JOINT,
    severity: VitalPointSeverity.CRITICAL,
    baseDamage: 38,
    effects: [],
    description: {
      korean: "무릎 관절 파괴, 보행 불가",
      english: "Knee joint destruction, unable to walk",
      romanized: "mureup gwanjeol pagoe",
    },
    targetingDifficulty: 0.7,
    effectiveStances: [TrigramStance.TAE, TrigramStance.GON],
  },
  {
    id: "leg_right_shin",
    names: {
      korean: "우정강이",
      english: "Right Shin",
      romanized: "u-jeonggang-i",
    },
    position: { x: 110, y: 220 },
    category: VitalPointCategory.SKELETAL,
    severity: VitalPointSeverity.MODERATE,
    baseDamage: 26,
    effects: [],
    description: {
      korean: "정강이 골절",
      english: "Shin fracture",
      romanized: "jeonggang-i goljeol",
    },
    targetingDifficulty: 0.5,
    effectiveStances: [TrigramStance.GEON, TrigramStance.GAN],
  },
  {
    id: "leg_right_ankle",
    names: {
      korean: "우발목",
      english: "Right Ankle",
      romanized: "u-balmok",
    },
    position: { x: 110, y: 235 },
    category: VitalPointCategory.JOINT,
    severity: VitalPointSeverity.MAJOR,
    baseDamage: 28,
    effects: [],
    description: {
      korean: "발목 염좌 또는 골절",
      english: "Ankle sprain or fracture",
      romanized: "balmok yeomjwa",
    },
    targetingDifficulty: 0.6,
    effectiveStances: [TrigramStance.TAE, TrigramStance.GON],
  },
  {
    id: "leg_right_foot",
    names: {
      korean: "우발등",
      english: "Right Foot",
      romanized: "u-baldeung",
    },
    position: { x: 110, y: 245 },
    category: VitalPointCategory.SKELETAL,
    severity: VitalPointSeverity.MINOR,
    baseDamage: 18,
    effects: [],
    description: {
      korean: "발등 골절, 보행 곤란",
      english: "Foot fracture, walking difficulty",
      romanized: "baldeung goljeol",
    },
    targetingDifficulty: 0.5,
    effectiveStances: [TrigramStance.GON],
  },
  {
    id: "leg_right_calf",
    names: {
      korean: "우종아리",
      english: "Right Calf",
      romanized: "u-jong-ari",
    },
    position: { x: 112, y: 225 },
    category: VitalPointCategory.MUSCULAR,
    severity: VitalPointSeverity.MODERATE,
    baseDamage: 23,
    effects: [],
    description: {
      korean: "종아리 근육 손상",
      english: "Calf muscle damage",
      romanized: "jong-ari geunnyuk sonsang",
    },
    targetingDifficulty: 0.5,
    effectiveStances: [TrigramStance.SON, TrigramStance.GEON],
  },
  {
    id: "leg_right_achilles",
    names: {
      korean: "우아킬레스건",
      english: "Right Achilles Tendon",
      romanized: "u-akilleseugeon",
    },
    position: { x: 114, y: 238 },
    category: VitalPointCategory.MUSCULAR,
    severity: VitalPointSeverity.CRITICAL,
    baseDamage: 40,
    effects: [],
    description: {
      korean: "아킬레스건 파열, 이동 불가",
      english: "Achilles tendon rupture, cannot move",
      romanized: "akilleseugeon paryeol",
    },
    targetingDifficulty: 0.8,
    effectiveStances: [TrigramStance.LI, TrigramStance.GON],
  },
  {
    id: "leg_right_femoral_nerve",
    names: {
      korean: "우대퇴신경",
      english: "Right Femoral Nerve",
      romanized: "u-daetwe singyeong",
    },
    position: { x: 108, y: 180 },
    category: VitalPointCategory.NEUROLOGICAL,
    severity: VitalPointSeverity.MAJOR,
    baseDamage: 32,
    effects: [],
    description: {
      korean: "대퇴 신경 타격, 다리 마비",
      english: "Femoral nerve strike, leg paralysis",
      romanized: "daetwe singyeong tagyeok",
    },
    targetingDifficulty: 0.7,
    effectiveStances: [TrigramStance.LI, TrigramStance.SON],
  },
  {
    id: "leg_right_peroneal_nerve",
    names: {
      korean: "우비골신경",
      english: "Right Peroneal Nerve",
      romanized: "u-bigol singyeong",
    },
    position: { x: 112, y: 210 },
    category: VitalPointCategory.NEUROLOGICAL,
    severity: VitalPointSeverity.MODERATE,
    baseDamage: 27,
    effects: [],
    description: {
      korean: "비골 신경 타격, 발 기능 상실",
      english: "Peroneal nerve strike, foot function loss",
      romanized: "bigol singyeong tagyeok",
    },
    targetingDifficulty: 0.7,
    effectiveStances: [TrigramStance.LI],
  },
] as const;

/**
 * Gets vital points by body region.
 * 
 * @param region - Body region to filter by
 * @returns Array of vital points in that region
 * 
 * @public
 * @korean 부위별급소
 */
export function getVitalPointsByRegion(region: BodyRegion): readonly VitalPoint[] {
  // This is a simplified implementation - in production you'd map IDs to regions properly
  const regionPrefixes: Record<BodyRegion, string[]> = {
    [BodyRegion.HEAD]: ["head_"],
    [BodyRegion.NECK]: ["head_side_neck", "head_throat"],
    [BodyRegion.TORSO]: ["torso_"],
    [BodyRegion.LEFT_ARM]: ["arm_left_"],
    [BodyRegion.RIGHT_ARM]: ["arm_right_"],
    [BodyRegion.LEFT_LEG]: ["leg_left_"],
    [BodyRegion.RIGHT_LEG]: ["leg_right_"],
    [BodyRegion.CORE]: ["torso_solar_plexus", "torso_diaphragm", "torso_abs_center"],
  };

  const prefixes = regionPrefixes[region] || [];
  return VITAL_POINTS_DATA.filter((vp) =>
    prefixes.some((prefix) => vp.id.startsWith(prefix))
  );
}

/**
 * Gets total count of vital points.
 * 
 * @returns Total number of vital points
 * 
 * @public
 * @korean 급소총개수
 */
export function getTotalVitalPointsCount(): number {
  return VITAL_POINTS_DATA.length;
}

export default VITAL_POINTS_DATA;
